### ISSUE TITLE
gr_modtool: remove is broken

### ISSUE THREAD

**Issue by mrjacobagilbert** [gnuradio/gnuradio#1602]
Related to Issue #1577 `gr_modtool rm` was broken by b0912d31f1a2cfea93a5588898cae0c652cd89d4...

```
jacob@ubuntu:/opt/gnuradio/src/gr-pdu_utils$ gr_modtool rm
GNU Radio module name identified: pdu_utils
Traceback (most recent call last):
  File "/opt/gnuradio/bin/gr_modtool", line 46, in <module>
    main()
  File "/opt/gnuradio/bin/gr_modtool", line 37, in main
    modtool.setup(options, args)
  File "/opt/gnuradio/lib/python2.7/dist-packages/gnuradio/modtool/modtool_rm.py", line 49, in setup
    with SequenceCompleter():
TypeError: __init__() takes exactly 2 arguments (1 given)
```

**Comment by marcusmueller** [comment]
oooooh shoot. I've had that code in a feature branch going of that feature branch … hope I didn't gc my git repo yet (otherwise I'll have to reimplement). There should be a list of existing blocks there!
