### ISSUE TITLE
fft_filter & filter_delay: undefined behaviour / std::vector out of bounds access

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#1777]
see #1776.

- [x] `fft_filter`
- [ ] `filter_delay`
<pre>
       Start 232: qa_fft_filter

232: Test command: /usr/bin/sh "/home/marcus/src/gnuradio/build/gr-filter/python/filter/qa_fft_filter_test.sh"
232: Test timeout computed to be: 10000000
232: /usr/include/c++/7/bits/stl_vector.h:797: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = std::complex<float>; _Alloc = std::allocator<std::complex<float> >; std::vector<_Tp, _Alloc>::reference = std::complex<float>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
232: /home/marcus/src/gnuradio/build/gr-filter/python/filter/qa_fft_filter_test.sh: line 9: 28121 Aborted                 (core dumped) /usr/bin/python2 -B /home/marcus/src/gnuradio/gr-filter/python/filter/qa_fft_filter.py
232/345 Test #232: qa_fft_filter ......................................***Failed    0.73 sec

        Start 233: qa_filter_delay_fc

233: Test command: /usr/bin/sh "/home/marcus/src/gnuradio/build/gr-filter/python/filter/qa_filter_delay_fc_test.sh"
233: Test timeout computed to be: 10000000
233: /usr/include/c++/7/bits/stl_vector.h:797: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = const void*; _Alloc = std::allocator<const void*>; std::vector<_Tp, _Alloc>::reference = const void*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
233: /home/marcus/src/gnuradio/build/gr-filter/python/filter/qa_filter_delay_fc_test.sh: line 9: 28129 Aborted                 (core dumped) /usr/bin/python2 -B /home/marcus/src/gnuradio/gr-filter/python/filter/qa_filter_delay_fc.py
233/345 Test #233: qa_filter_delay_fc .................................***Failed    0.60 sec
</pre>

**Comment by marcusmueller** [comment]
backtracing the fft_filter

<pre>
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6cbb800 in __GI_abort () at abort.c:89
#2  0x00007fffe91538da in std::__replacement_assert(char const*, int, char const*, char const*) () from /home/marcus/src/gnuradio/build/gr-filter/lib/libgnuradio-filter-3.7.12.0.so.0.0.0
#3  0x00007fffe91554ef in std::vector<std::complex<float>, std::allocator<std::complex<float> > >::operator[](unsigned long) ()
   from /home/marcus/src/gnuradio/build/gr-filter/lib/libgnuradio-filter-3.7.12.0.so.0.0.0
#4  0x00007fffe915b5e4 in gr::filter::kernel::fft_filter_ccc::filter(int, std::complex<float> const*, std::complex<float>*) ()
   from /home/marcus/src/gnuradio/build/gr-filter/lib/libgnuradio-filter-3.7.12.0.so.0.0.0
#5  0x00007fffe91a776e in gr::filter::fft_filter_ccc_impl::work(int, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&) ()
   from /home/marcus/src/gnuradio/build/gr-filter/lib/libgnuradio-filter-3.7.12.0.so.0.0.0
#6  0x00007ffff62284ad in gr::sync_decimator::general_work(int, std::vector<int, std::allocator<int> >&, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&) () from /home/marcus/src/gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#7  0x00007ffff61d7272 in gr::block_executor::run_one_iteration() () from /home/marcus/src/gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#8  0x00007ffff6232894 in gr::tpb_thread_body::tpb_thread_body(boost::shared_ptr<gr::block>, boost::shared_ptr<boost::barrier>, int) ()
   from /home/marcus/src/gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#9  0x00007ffff6222cc6 in gr::tpb_container::operator()() () from /home/marcus/src/gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#10 0x00007ffff6223f5c in gr::thread::thread_body_wrapper<gr::tpb_container>::operator()() () from /home/marcus/src/gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#11 0x00007ffff6223d47 in boost::detail::function::void_function_obj_invoker0<gr::thread::thread_body_wrapper<gr::tpb_container>, void>::invoke(boost::detail::function::function_buffer&) ()
   from /home/marcus/src/gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#12 0x00007ffff61b3d6e in boost::function0<void>::operator()() const () from /home/marcus/src/gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#13 0x00007ffff61b3d18 in boost::detail::thread_data<boost::function0<void> >::run() () from /home/marcus/src/gnuradio/build/gnuradio-runtime/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#14 0x00007ffff4e4c2fd in boost::(anonymous namespace)::thread_proxy (param=<optimized out>) at libs/thread/src/pthread/thread.cpp:171
#15 0x00007ffff777c36d in start_thread (arg=0x7fffe371a700) at pthread_create.c:456
#16 0x00007ffff6d93b4f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
</pre>
