### ISSUE TITLE
Constellation Object and Constellation Rect. Object are broken

### ISSUE THREAD

**Issue by argilo** [gnuradio/gnuradio#2050]
On the master branch, the Constellation Object and Constellation Rect. Object blocks (from the "Modulators" category) cannot be added to a flow graph. When adding the Constellation Object, I see the following errors at the console:
```
Traceback (most recent call last):
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 59, in _get_template
    return self._template_cache[str(text)]
KeyError: '% if str(type) == "calcdist":\nself.${id} = ${id} = digital.constellation_calcdist(${const_points}, ${sym_map},\n${rot_sym}, ${dims}).base()\n% else:\nself.${id} = ${id} = digital.constellation_${type}().base()\n% endif\n% if str(soft_dec_lut).lower() == \'\'"auto"\'\' or str(soft_dec_lut).lower() == "\'\'auto\'\'":\nself.${id}.gen_soft_dec_lut(${precision})\n% elif str(soft_dec_lut) != \'\'None\'\':\nself.${id}.set_soft_dec_lut(${soft_dec_lut}, ${precision})\n% endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mako/pyparser.py", line 41, in parse
    return _ast_util.parse(code, '<unknown>', mode)
  File "/usr/lib/python3/dist-packages/mako/_ast_util.py", line 84, in parse
    return compile(expr, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    elif str(soft_dec_lut) != ''None'':pass
                                   ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 50, in compile
    template = Template(text)
  File "/usr/lib/python3/dist-packages/mako/template.py", line 320, in __init__
    (code, module) = _compile_text(self, text, filename)
  File "/usr/lib/python3/dist-packages/mako/template.py", line 705, in _compile_text
    generate_magic_comment=template.disable_unicode)
  File "/usr/lib/python3/dist-packages/mako/template.py", line 685, in _compile
    node = lexer.parse()
  File "/usr/lib/python3/dist-packages/mako/lexer.py", line 243, in parse
    if self.match_control_line():
  File "/usr/lib/python3/dist-packages/mako/lexer.py", line 435, in match_control_line
    self.append_node(parsetree.ControlLine, keyword, isend, text)
  File "/usr/lib/python3/dist-packages/mako/lexer.py", line 140, in append_node
    node = nodecls(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mako/parsetree.py", line 83, in __init__
    code = ast.PythonFragment(text, **self.exception_kwargs)
  File "/usr/lib/python3/dist-packages/mako/ast.py", line 105, in __init__
    super(PythonFragment, self).__init__(code, **exception_kwargs)
  File "/usr/lib/python3/dist-packages/mako/ast.py", line 40, in __init__
    expr = pyparser.parse(code.lstrip(), "exec", **exception_kwargs)
  File "/usr/lib/python3/dist-packages/mako/pyparser.py", line 48, in parse
    ), **exception_kwargs)
mako.exceptions.SyntaxException: (SyntaxError) invalid syntax (<unknown>, line 2) ("if False:pass\nelif str(soft_dec_lut) != ''None'':p") at line: 9 char: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 74, in render
    template = self._get_template(text)
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 61, in _get_template
    return self.compile(text)
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 52, in compile
    raise TemplateError(text, *error.args)
gnuradio.grc.core.errors.TemplateError: ('% if str(type) == "calcdist":\nself.${id} = ${id} = digital.constellation_calcdist(${const_points}, ${sym_map},\n${rot_sym}, ${dims}).base()\n% else:\nself.${id} = ${id} = digital.constellation_${type}().base()\n% endif\n% if str(soft_dec_lut).lower() == \'\'"auto"\'\' or str(soft_dec_lut).lower() == "\'\'auto\'\'":\nself.${id}.gen_soft_dec_lut(${precision})\n% elif str(soft_dec_lut) != \'\'None\'\':\nself.${id}.set_soft_dec_lut(${soft_dec_lut}, ${precision})\n% endif', '(SyntaxError) invalid syntax (<unknown>, line 2) ("if False:pass\\nelif str(soft_dec_lut) != \'\'None\'\':p") at line: 9 char: 1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/gui/Application.py", line 422, in _handle_action
    flow_graph_update()
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/gui/Application.py", line 132, in flow_graph_update
    fg.update()
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 174, in update
    self.rewrite()
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/FlowGraph.py", line 181, in rewrite
    self.renew_namespace()
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/FlowGraph.py", line 212, in renew_namespace
    for variable_block in self.get_variables():
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/FlowGraph.py", line 79, in get_variables
    return expr_utils.sort_objects(variables, attrgetter('name'), methodcaller('get_var_make'))
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/utils/expr_utils.py", line 74, in sort_objects
    id2expr = {get_id(obj): get_expr(obj) for obj in objects}
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/utils/expr_utils.py", line 74, in <dictcomp>
    id2expr = {get_id(obj): get_expr(obj) for obj in objects}
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/blocks/block.py", line 228, in get_var_make
    return self.templates.render('var_make')
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 77, in render
    raise TemplateError(error, text)
gnuradio.grc.core.errors.TemplateError: (TemplateError('% if str(type) == "calcdist":\nself.${id} = ${id} = digital.constellation_calcdist(${const_points}, ${sym_map},\n${rot_sym}, ${dims}).base()\n% else:\nself.${id} = ${id} = digital.constellation_${type}().base()\n% endif\n% if str(soft_dec_lut).lower() == \'\'"auto"\'\' or str(soft_dec_lut).lower() == "\'\'auto\'\'":\nself.${id}.gen_soft_dec_lut(${precision})\n% elif str(soft_dec_lut) != \'\'None\'\':\nself.${id}.set_soft_dec_lut(${soft_dec_lut}, ${precision})\n% endif', '(SyntaxError) invalid syntax (<unknown>, line 2) ("if False:pass\\nelif str(soft_dec_lut) != \'\'None\'\':p") at line: 9 char: 1'), '% if str(type) == "calcdist":\nself.${id} = ${id} = digital.constellation_calcdist(${const_points}, ${sym_map},\n${rot_sym}, ${dims}).base()\n% else:\nself.${id} = ${id} = digital.constellation_${type}().base()\n% endif\n% if str(soft_dec_lut).lower() == \'\'"auto"\'\' or str(soft_dec_lut).lower() == "\'\'auto\'\'":\nself.${id}.gen_soft_dec_lut(${precision})\n% elif str(soft_dec_lut) != \'\'None\'\':\nself.${id}.set_soft_dec_lut(${soft_dec_lut}, ${precision})\n% endif')
```

**Comment by haakov** [comment]
@argilo I've posted a PR for this issue: https://github.com/gnuradio/gnuradio/pull/2058
