### ISSUE TITLE
Struct Variable block is broken

### ISSUE THREAD

**Issue by argilo** [gnuradio/gnuradio#2051]
On the master branch, dropping a Struct Variable block (from the "Variables" category) into a flowgraph in GRC results in the following error:
```
Traceback (most recent call last):
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 75, in render
    return template.render(**namespace)
  File "/usr/lib/python3/dist-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7fbe94529cf8", line 33, in render_body
TypeError: 'Undefined' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/gui/Application.py", line 422, in _handle_action
    flow_graph_update()
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/gui/Application.py", line 132, in flow_graph_update
    fg.update()
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 174, in update
    self.rewrite()
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/FlowGraph.py", line 181, in rewrite
    self.renew_namespace()
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/FlowGraph.py", line 212, in renew_namespace
    for variable_block in self.get_variables():
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/FlowGraph.py", line 79, in get_variables
    return expr_utils.sort_objects(variables, attrgetter('name'), methodcaller('get_var_make'))
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/utils/expr_utils.py", line 74, in sort_objects
    id2expr = {get_id(obj): get_expr(obj) for obj in objects}
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/utils/expr_utils.py", line 74, in <dictcomp>
    id2expr = {get_id(obj): get_expr(obj) for obj in objects}
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/blocks/block.py", line 228, in get_var_make
    return self.templates.render('var_make')
  File "/home/argilo/prefix_next/lib/python3.6/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 77, in render
    raise TemplateError(error, text)
gnuradio.grc.core.errors.TemplateError: (TypeError("'Undefined' object is not callable",), "self.${id} = ${id} = struct({\n    % for i in range(20):\n    <%\n        field = getVar('field' + str(i))\n    %>\n    % if len(str(field)) > 2:\n    ${field}: getVar('value' + str(i)),\n    % endif\n    % endfor\n})")
```

**Comment by haakov** [comment]
Interesting! Caused by `getVar()`
