### ISSUE TITLE
UHD: uhd sink fails with errror message.

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#2219]
```
Traceback (most recent call last):
  File "/home/re/xfer/top_block.py", line 248, in <module>
    main()
  File "/home/re/xfer/top_block.py", line 236, in main
    tb = top_block_cls()
  File "/home/re/xfer/top_block.py", line 90, in __init__
    '',
  File "/opt/gnuradio-3.7.12git/lib/python3.6/dist-packages/gnuradio/uhd/__init__.py", line 119, in constructor_interceptor
    args[index] = cast(args[index])
  File "/opt/gnuradio-3.7.12git/lib/python3.6/dist-packages/gnuradio/uhd/uhd_swig.py", line 1275, in __init__
    this = _uhd_swig.new_io_type_t(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_io_type_t'.
  Possible C/C++ prototypes are:
    uhd::io_type_t::io_type_t(uhd::io_type_t::tid_t)
    uhd::io_type_t::io_type_t(size_t)


>>> Done (return code 1)
```

**Comment by drmpeg** [comment]
Fixed by commit in pull request #2220.
