### ISSUE TITLE
qa: moving_average flakiness

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#2242]
```
205/360 Test #205: qa_moving_average ..................................***Failed    0.69 sec
...F
======================================================================
FAIL: test_04 (__main__.test_moving_average)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cache/workdir/Ubuntu_16_04_64_remote_0/build_Ubuntu_16_04_64/src/gr-blocks/python/blocks/qa_moving_average.py", line 155, in test_04
    self.assertComplexTuplesAlmostEqual(expected_result, dst_data, 4)
  File "/cache/workdir/Ubuntu_16_04_64_remote_0/build_Ubuntu_16_04_64/src/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 86, in assertComplexTuplesAlmostEqual
    self.assertComplexAlmostEqual (a[i], b[i], places, msg)
  File "/cache/workdir/Ubuntu_16_04_64_remote_0/build_Ubuntu_16_04_64/src/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 54, in assertComplexAlmostEqual
    msg or '%r != %r within %r places' % (first, second, places))
AssertionError: (-11.104617556156482-11.9834404148583j) != (-11.104567527770996-11.983440399169922j) within 4 places
----------------------------------------------------------------------
Ran 4 tests in 0.170s
FAILED (failures=1)
```

Build: https://ci.gnuradio.org/buildbot/#/builders/49/builds/405/steps/7/logs/stdio

**Comment by mbr0wn** [comment]
I have not seen this fail in a long time -- closing.
