### ISSUE TITLE
alloc-dealloc mismatch in tcp_server_sink_impl

### ISSUE THREAD

**Issue by dlrobertson** [gnuradio/gnuradio#2247]
# Summary

A mismatching smart pointer type in `tcp_server_sink_impl` is causing a alloc-dealloc
mismatch.

# Details

The `tcp_server_sink_impl` structure contains the `shared_ptr` `d_buf`. It is initialized
with the following:

```c++
boost::shared_ptr<uint8_t> d_buf;
```

Which results in the following:

```
==9826==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0x7fc6481da800
    #0 0x7fc656af35e0 in operator delete(void*) /var/tmp/portage/sys-devel/gcc-8.2.0-r5/work/gcc-8.2.0/libsanitizer/asan/asan_new_delete.cc:135
    #1 0x7fc64d752534 in boost::detail::sp_counted_base::release() /usr/include/boost/smart_ptr/detail/sp_counted_base_std_atomic.hpp:110
    #2 0x7fc64da3f723 in boost::detail::shared_count::~shared_count() /usr/include/boost/smart_ptr/detail/shared_count.hpp:426
    #3 0x7fc64da3f723 in boost::shared_ptr<unsigned char>::~shared_ptr() /usr/include/boost/smart_ptr/shared_ptr.hpp:341
    #4 0x7fc64da3f723 in gr::blocks::tcp_server_sink_impl::~tcp_server_sink_impl() ../gr-blocks/lib/tcp_server_sink_impl.cc:113
    #5 0x7fc64da3fa90 in gr::blocks::tcp_server_sink_impl::~tcp_server_sink_impl() ../gr-blocks/lib/tcp_server_sink_impl.cc:129
    #6 0x7fc651a62b85 in boost::detail::sp_counted_base::release() /usr/include/boost/smart_ptr/detail/sp_counted_base_std_atomic.hpp:110
    #7 0x7fc651a62b85 in boost::detail::shared_count::~shared_count() /usr/include/boost/smart_ptr/detail/shared_count.hpp:426
    #8 0x7fc651a62b85 in boost::shared_ptr<gr::basic_block>::~shared_ptr() /usr/include/boost/smart_ptr/shared_ptr.hpp:341
    #9 0x7fc651a62b85 in gr::endpoint::~endpoint() ../gnuradio-runtime/include/gnuradio/flowgraph.h:37
    #10 0x7fc651a62b85 in gr::edge::~edge() ../gnuradio-runtime/lib/flowgraph.cc:36
    #11 0x7fc651a634eb in void std::_Destroy<gr::edge>(gr::edge*) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_construct.h:98
    #12 0x7fc651a634eb in void std::_Destroy_aux<false>::__destroy<gr::edge*>(gr::edge*, gr::edge*) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_construct.h:108
    #13 0x7fc651a634eb in void std::_Destroy<gr::edge*>(gr::edge*, gr::edge*) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_construct.h:137
    #14 0x7fc651a634eb in void std::_Destroy<gr::edge*, gr::edge>(gr::edge*, gr::edge*, std::allocator<gr::edge>&) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_construct.h:206
    #15 0x7fc651a634eb in std::vector<gr::edge, std::allocator<gr::edge> >::_M_erase_at_end(gr::edge*) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_vector.h:1658
    #16 0x7fc651a634eb in std::vector<gr::edge, std::allocator<gr::edge> >::clear() /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_vector.h:1386
    #17 0x7fc651a634eb in gr::flowgraph::clear() ../gnuradio-runtime/lib/flowgraph.cc:128
    #18 0x7fc651a9e16f in gr::hier_block2_detail::disconnect_all() ../gnuradio-runtime/lib/hier_block2_detail.cc:518
    #19 0x7fc651a98230 in gr::hier_block2::~hier_block2() ../gnuradio-runtime/lib/hier_block2.cc:60
    #20 0x7fc651b2de50 in gr::top_block::~top_block() ../gnuradio-runtime/lib/top_block.cc:57
...
```

# The fix

The fix should be as easy as changing `uint8_t` to `uint8_t[]`. From the the
[Boost `shared_ptr` docs]:

> Starting with Boost release 1.53, shared_ptr can be used to hold a pointer to a dynamically
> allocated array. This is accomplished by using an array type (T[] or T[N]) as the template parameter.

[Boost `shared_ptr` docs]: https://www.boost.org/doc/libs/1_65_0/libs/smart_ptr/doc/html/smart_ptr.html#shared_ptr

**Comment by mbr0wn** [comment]
Closed via #2248.
