### ISSUE TITLE
alloc-dealloc mismatch pfb_decimator_ccf_impl

### ISSUE THREAD

**Issue by dlrobertson** [gnuradio/gnuradio#2249]
The `d_rotator` member of `pfb_decimator_ccf_impl` is allocated with `new[]` but deallocated with `delete`in the destructor.

```
==3866==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0x604000027890
    #0 0x7fc6efc4e5e0 in operator delete(void*) /var/tmp/portage/sys-devel/gcc-8.2.0-r5/work/gcc-8.2.0/libsanitizer/asan/asan_new_delete.cc:135
    #1 0x7fc6e79e3596 in gr::filter::pfb_decimator_ccf_impl::~pfb_decimator_ccf_impl() ../gr-filter/lib/pfb_decimator_ccf_impl.cc:101
    #2 0x7fc6e79e3680 in gr::filter::pfb_decimator_ccf_impl::~pfb_decimator_ccf_impl() ../gr-filter/lib/pfb_decimator_ccf_impl.cc:102
    #3 0x7fc6eabe2c54 in boost::detail::sp_counted_base::release() /usr/include/boost/smart_ptr/detail/sp_counted_base_std_atomic.hpp:110
    #4 0x7fc6eabe2c54 in boost::detail::shared_count::~shared_count() /usr/include/boost/smart_ptr/detail/shared_count.hpp:426
    #5 0x7fc6eabe2c54 in boost::shared_ptr<gr::basic_block>::~shared_ptr() /usr/include/boost/smart_ptr/shared_ptr.hpp:341
    #6 0x7fc6eabe2c54 in gr::endpoint::~endpoint() ../gnuradio-runtime/include/gnuradio/flowgraph.h:37
    #7 0x7fc6eabe2c54 in gr::edge::~edge() ../gnuradio-runtime/lib/flowgraph.cc:36
    #8 0x7fc6eabe34eb in void std::_Destroy<gr::edge>(gr::edge*) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_construct.h:98
    #9 0x7fc6eabe34eb in void std::_Destroy_aux<false>::__destroy<gr::edge*>(gr::edge*, gr::edge*) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_construct.h:108
    #10 0x7fc6eabe34eb in void std::_Destroy<gr::edge*>(gr::edge*, gr::edge*) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_construct.h:137
    #11 0x7fc6eabe34eb in void std::_Destroy<gr::edge*, gr::edge>(gr::edge*, gr::edge*, std::allocator<gr::edge>&) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_construct.h:206
    #12 0x7fc6eabe34eb in std::vector<gr::edge, std::allocator<gr::edge> >::_M_erase_at_end(gr::edge*) /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_vector.h:1658
    #13 0x7fc6eabe34eb in std::vector<gr::edge, std::allocator<gr::edge> >::clear() /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_vector.h:1386
    #14 0x7fc6eabe34eb in gr::flowgraph::clear() ../gnuradio-runtime/lib/flowgraph.cc:128
    #15 0x7fc6eac1e16f in gr::hier_block2_detail::disconnect_all() ../gnuradio-runtime/lib/hier_block2_detail.cc:518
    #16 0x7fc6eac18230 in gr::hier_block2::~hier_block2() ../gnuradio-runtime/lib/hier_block2.cc:60
    #17 0x7fc6eacade50 in gr::top_block::~top_block() ../gnuradio-runtime/lib/top_block.cc:57
    #18 0x7fc6eaf1cfa4 in boost::detail::sp_counted_base::release() /usr/include/boost/smart_ptr/detail/sp_counted_base_std_atomic.hpp:110
    #19 0x7fc6eaf1cfa4 in boost::detail::shared_count::~shared_count() /usr/include/boost/smart_ptr/detail/shared_count.hpp:426
    #20 0x7fc6eaf1cfa4 in boost::shared_ptr<gr::top_block>::~shared_ptr() /usr/include/boost/smart_ptr/shared_ptr.hpp:341
    #21 0x7fc6eaf1cfa4 in _wrap_delete_top_block_sptr gnuradio-runtime/swig/runtime_swigPYTHON_wrap.cxx:48828
```

**Comment by mbr0wn** [comment]
Closed via #2248.
