### ISSUE TITLE
GRC: GUI Hints are broken

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#2287]
To reproduce: Open uhd_msg_tune.grc, add a GUI hint ot the frequency sink, then:
```
Traceback (most recent call last):
  File "/home/mbr0wn/.usrlocal-gnuradio/lib/python3.5/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 75, in render
    return template.render(**namespace)
  File "/usr/local/lib/python3.5/dist-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python3.5/dist-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python3.5/dist-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7fb233df3860", line 260, in render_body
TypeError: unsupported operand type(s) for %: 'NoneType' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mbr0wn/.usrlocal-gnuradio/lib/python3.5/dist-packages/gnuradio/grc/gui/ParamWidgets.py", line 119, in _apply_change
    self._changed_callback(self, None)
  File "/home/mbr0wn/.usrlocal-gnuradio/lib/python3.5/dist-packages/gnuradio/grc/gui/PropsDialog.py", line 158, in _handle_changed
    self.update_gui()
  File "/home/mbr0wn/.usrlocal-gnuradio/lib/python3.5/dist-packages/gnuradio/grc/gui/PropsDialog.py", line 205, in update_gui
    self._update_docs_page()
  File "/home/mbr0wn/.usrlocal-gnuradio/lib/python3.5/dist-packages/gnuradio/grc/gui/PropsDialog.py", line 229, in _update_docs_page
    block_constructor = self._block.templates.render('make').rsplit('.', 2)[-1]
  File "/home/mbr0wn/.usrlocal-gnuradio/lib/python3.5/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 77, in render
    raise TemplateError(error, text)
gnuradio.grc.core.errors.TemplateError: (TypeError("unsupported operand type(s) for %: 'NoneType' and 'str'",), '<%\n    win = \'self._%s_win\'%id\n%>\\\nqtgui.${type.fcn}(\n    ${fftsize}, #size\n    ${wintype}, #wintype\n    ${fc}, #fc\n    ${bw}, #bw\n    ${name}, #name\n    ${ 0 if (type == \'msg_complex\' or type == \'msg_float\') else nconnections }\n)\nself.${id}.set_update_time(${update_time})\nself.${id}.set_y_axis(${ymin}, ${ymax})\nself.${id}.set_y_label(${label}, ${units})\nself.${id}.set_trigger_mode(${tr_mode}, ${tr_level}, ${tr_chan}, ${tr_tag})\nself.${id}.enable_autoscale(${autoscale})\nself.${id}.enable_grid(${grid})\nself.${id}.set_fft_average(${average})\nself.${id}.enable_axis_labels(${axislabels})\nself.${id}.enable_control_panel(${ctrlpanel})\n\n% if legend == "False":\nself.${id}.disable_legend()\n% endif\n\n% if type == "float" or type == "msg_float":\nself.${id}.set_plot_pos_half(not ${freqhalf})\n% endif\n\nlabels = [${label1}, ${label2}, ${label3}, ${label4}, ${label5},\n    ${label6}, ${label7}, ${label8}, ${label9}, ${label10}]\nwidths = [${width1}, ${width2}, ${width3}, ${width4}, ${width5},\n    ${width6}, ${width7}, ${width8}, ${width9}, ${width10}]\ncolors = [${color1}, ${color2}, ${color3}, ${color4}, ${color5},\n    ${color6}, ${color7}, ${color8}, ${color9}, ${color10}]\nalphas = [${alpha1}, ${alpha2}, ${alpha3}, ${alpha4}, ${alpha5},\n    ${alpha6}, ${alpha7}, ${alpha8}, ${alpha9}, ${alpha10}]\n\nfor i in range(${1 if (type == \'msg_complex\' or type == \'msg_float\') else nconnections}):\n    if len(labels[i]) == 0:\n        self.${id}.set_line_label(i, "Data {0}".format(i))\n    else:\n        self.${id}.set_line_label(i, labels[i])\n    self.${id}.set_line_width(i, widths[i])\n    self.${id}.set_line_color(i, colors[i])\n    self.${id}.set_line_alpha(i, alphas[i])\n\n${win} = sip.wrapinstance(self.${id}.pyqwidget(), Qt.QWidget)\n${ gui_hint() % win}')
```

**Comment by haakov** [comment]
To me this looks like a collision is detected, however the exception isn't handled or passed on to the user in any way, and `parse_gui_hint()` ends up returning None:

https://github.com/gnuradio/gnuradio/blob/ee8e03c04e1c1b89fc429848308020b0bc2c7e23/grc/core/params/param.py#L378

What did you enter as the GUI hint?

**Comment by mbr0wn** [comment]
I put `0,0,3,3` into the frequency sink.

**Comment by haakov** [comment]
Okay, so I guess this could be added to grc/core/params/dtypes.py:
```
@validates('gui_hint')
def validate_gui_hint(param):
    try:
        param.parse_gui_hint(param.value)
    except Exception as e:
        raise ValidateError(str(e))
```

**Comment by haakov** [comment]
Also, I'm a bit surprised to see this:

https://github.com/gnuradio/gnuradio/blob/7074f054c25a69392e7ae4e1f0204a1c5ce242f8/grc/gui/PropsDialog.py#L208-L239

Isn't the YAML files' `documentation` key the only source for the blocks' documentation tab in GRC?
