### ISSUE TITLE
New gr_modtool fails cmake

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#2290]
I gave the new gr_modtool a try, and I'm getting this error during the cmake phase.
```
-- The CXX compiler identification is GNU 7.3.0
-- The C compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
CMake Deprecation Warning at CMakeLists.txt:55 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   system
--   unit_test_framework
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
CMake Error at CMakeLists.txt:142 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.7.2".

  The following configuration files were considered but not accepted:

    /opt/gnuradio-3.7.12git/lib/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.git.0



-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/xfer/gr-iqlevels/build/CMakeFiles/CMakeOutput.log".
```

**Comment by drmpeg** [comment]
Then the make fails.
```
Scanning dependencies of target gnuradio-iqlevels
[  4%] Building CXX object lib/CMakeFiles/gnuradio-iqlevels.dir/iqlevels_impl.cc.o
[  9%] Linking CXX shared library libgnuradio-iqlevels-1.0.0git.so
[  9%] Built target gnuradio-iqlevels
Scanning dependencies of target pygen_apps_9a6dd
[  9%] Built target pygen_apps_9a6dd
Scanning dependencies of target doxygen_target
[ 14%] Generating documentation with doxygen
[ 14%] Built target doxygen_target
Scanning dependencies of target _iqlevels_swig_doc_tag
[ 19%] Building CXX object swig/CMakeFiles/_iqlevels_swig_doc_tag.dir/_iqlevels_swig_doc_tag.cpp.o
[ 23%] Linking CXX executable _iqlevels_swig_doc_tag
[ 23%] Built target _iqlevels_swig_doc_tag
Scanning dependencies of target iqlevels_swig_swig_doc
[ 28%] Generating doxygen xml for iqlevels_swig_doc docs
[ 33%] Generating python docstrings for iqlevels_swig_doc
Traceback (most recent call last):
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/swig_doc.py", line 330, in <module>
    make_swig_interface_file(di, swigdocfilename, custom_output=custom_output)
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/swig_doc.py", line 253, in make_swig_interface_file
    blocks = di.in_category(Block)
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/base.py", line 143, in in_category
    self.confirm_no_error()
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/base.py", line 209, in confirm_no_error
    self.check_parsed()
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/base.py", line 206, in check_parsed
    self._parse()
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/doxyindex.py", line 57, in _parse
    self._members += converted.members()
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/base.py", line 177, in members
    self.confirm_no_error()
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/base.py", line 209, in confirm_no_error
    self.check_parsed()
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/base.py", line 206, in check_parsed
    self._parse()
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/doxyindex.py", line 242, in _parse
    self.set_descriptions(self._retrieved_data.compounddef)
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/doxyindex.py", line 84, in set_descriptions
    bd = description(getattr(parse_data, 'briefdescription', None))
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/text.py", line 40, in description
    return description_bit(obj).strip()
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/text.py", line 47, in description_bit
    contents = [description_bit(item) for item in obj.content_]
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/text.py", line 50, in description_bit
    result = description_bit(obj.value)
  File "/home/ubuntu/xfer/gr-iqlevels/docs/doxygen/doxyxml/text.py", line 54, in description_bit
    raise Exception('Expecting a string or something with content, content_ or value attribute')
Exception: Expecting a string or something with content, content_ or value attribute
swig/CMakeFiles/iqlevels_swig_swig_doc.dir/build.make:60: recipe for target 'swig/iqlevels_swig_doc.i' failed
make[2]: *** [swig/iqlevels_swig_doc.i] Error 1
CMakeFiles/Makefile2:327: recipe for target 'swig/CMakeFiles/iqlevels_swig_swig_doc.dir/all' failed
make[1]: *** [swig/CMakeFiles/iqlevels_swig_swig_doc.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by drmpeg** [comment]
Also, the argument entry wraps around on itself.

![image](https://user-images.githubusercontent.com/5397196/50721772-c7c25600-1079-11e9-834e-88d09425f7bb.png)

**Comment by mbr0wn** [comment]
Well the old modtool also failed (See #2075). Not that that makes anything any better...

**Comment by drmpeg** [comment]
Outdated.
