### ISSUE TITLE
gr-ctrlport-monitor qtgui semilogy fails to display

### ISSUE THREAD

**Issue by oscarmezyk** [gnuradio/gnuradio#2362]
Version 3.7.13.4
Thrift version 0.10.0

I had issues running gr-ctrlport monitor&performance monitor. These programs needed graphviz, pygraphviz, networkx packages that needed to be installed manually for python2.7.  After rebuilding gnuradio with enabled performance monitoring and installing dependencies I came to the point I don't know how to fix:

```
Traceback (most recent call last):
  File "/home/oskar/gnurf/bin/gr-ctrlport-monitor", line 191, in newSub
    log, strip, stem)
  File "/home/oskar/gnurf/bin/gr-ctrlport-monitor", line 272, in newPlotF
    plot.semilogy(logy)
  File "/home/oskar/gnurf/lib/python2.7/dist-packages/gnuradio/ctrlport/GrDataPlotter.py", line 106, in semilogy
    self.snk.enable_semilogy(en)
  File "/home/oskar/gnurf/lib/python2.7/dist-packages/gnuradio/qtgui/qtgui_swig.py", line 5612, in enable_semilogy
    return _qtgui_swig.time_sink_f_sptr_enable_semilogy(self, en)
TypeError: in method 'time_sink_f_sptr_enable_semilogy', argument 2 of type 'bool'
```
The result is that I can't get displays in gr-ctrlport-monitor - either run in gr-companion or as standalone application.

Any hints?
Thanks

**Comment by marcusmueller** [comment]
d
