### ISSUE TITLE
GRC: QT GUI Range from old grc file, Error: 'id'

### ISSUE THREAD

**Issue by nickoe** [gnuradio/gnuradio#2391]
When I open a grc file in XML format from gnuradio 3.7 I get this error:
```
Loading: "/tmp/untitled.grc"
>>> Converting from XML
Block id "variable_qtgui_range" not found
Error: 'id'
>>> Failure
Traceback (most recent call last):
  File "/usr/local/gr37/lib/python3.7/dist-packages/gnuradio/grc/gui/MainWindow.py", line 261, in new_page
    file_path=file_path,
  File "/usr/local/gr37/lib/python3.7/dist-packages/gnuradio/grc/gui/Notebook.py", line 107, in __init__
    flow_graph.import_data(initial_state)
  File "/usr/local/gr37/lib/python3.7/dist-packages/gnuradio/grc/core/FlowGraph.py", line 381, in import_data
    block.import_data(**block_data)
  File "/usr/local/gr37/lib/python3.7/dist-packages/gnuradio/grc/core/blocks/block.py", line 448, in import_data
    self.params['id'].value = name
KeyError: 'id'
```
Using 3.8tech-preview-298-g61ebd24c4 with python3.
![image](https://user-images.githubusercontent.com/352202/53987054-1e065080-4120-11e9-91a9-abe52ccd79ac.png)

Test file:
[untitled.txt (you may rename this to .grc)](https://github.com/gnuradio/gnuradio/files/2943211/untitled.txt)

**Comment by nickoe** [comment]
This may be partly du to https://github.com/gnuradio/gnuradio/pull/2278 not being merged yet, partly due to gr-qtgui not being enabled in my build caused by https://github.com/gnuradio/gnuradio/issues/2208#issuecomment-470692964.

I will rebuild and test.

**Comment by nickoe** [comment]
Ok, I confirm that it works when I actually got gr-qtgui built in as well. :)
