### ISSUE TITLE
gr-modtool: Update gr_modtool info for the 3.8 release

### ISSUE THREAD

**Issue by swap-nil7** [gnuradio/gnuradio#2403]
We need to update the API version in the `gr_modtool info` for the `3.8 release`.

**Comment by mormj** [comment]
Running gr_modtool info with the latest 3.8, I get the following:

Traceback (most recent call last):
  File "/share/gnuradio/grdev/bin/gr_modtool", line 30, in <module>
    cli()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/share/gnuradio/grdev/lib/python3.6/dist-packages/gnuradio/modtool/cli/base.py", line 149, in wrapper
    return func(*args, **kwargs)
  File "/share/gnuradio/grdev/lib/python3.6/dist-packages/gnuradio/modtool/cli/info.py", line 42, in cli
    run(self)
  File "/share/gnuradio/grdev/lib/python3.6/dist-packages/gnuradio/modtool/cli/base.py", line 168, in run
    module.run()
  File "/share/gnuradio/grdev/lib/python3.6/dist-packages/gnuradio/modtool/core/info.py", line 50, in run
    raise ModToolException('{}' if self._python_readable else "No module found.")
gnuradio.modtool.core.base.ModToolException: No module found.

**Comment by mormj** [comment]
I can dig into this if no one is actively debugging this issue

**Comment by mormj** [comment]
@swap-nil7 - there is code already in there which does this but was in only one of two places where the version is being checked:

```
        if not os.path.isfile(os.path.join('cmake', 'Modules', 'FindCppUnit.cmake')):
            self.info['version'] = '38'
```
If I copy this to run() in core/info.py the version will pop up consistent with previous versions of the modtool info which is "post-3.8"

@marcusmueller - Is the idea with this issue just to continue with the modtool versioning as done in the past, i.e., "post-3.8"?  If so, this appears to be a simple fix.

**Comment by swap-nil7** [comment]
Yes, I guess that's a correct fix.

**Comment by mormj** [comment]
By the way, nice work @swap-nil7 on the modtool refresh!
