### ISSUE TITLE
Bug in whiten (within packet-decoder block)

### ISSUE THREAD

**Issue by phansel** [gnuradio/gnuradio#2444]
I'm not sure if this bug is still even applicable, as the "packet decoder" block has been deprecated. A minimal reproduction is [here.](https://github.com/gnuradio/gnuradio/files/3059085/packeterror.grc.txt)

```
Executing: /usr/bin/python -u /home/user/top_block.py

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/grc_gnuradio/blks2/packet.py", line 144, in run
    ok, payload = packet_utils.unmake_packet(msg.to_string(), int(msg.arg1()))
  File "/usr/lib/python2.7/dist-packages/gnuradio/digital/packet_utils.py", line 198, in unmake_packet
    payload_with_crc = dewhiten(whitened_payload_with_crc, whitener_offset)
  File "/usr/lib/python2.7/dist-packages/gnuradio/digital/packet_utils.py", line 95, in dewhiten
    return whiten(s, o)        # self inverse
  File "/usr/lib/python2.7/dist-packages/gnuradio/digital/packet_utils.py", line 91, in whiten
    z = sa ^ random_mask_vec8[o:len(sa)+o]
ValueError: operands could not be broadcast together with shapes (4095,) (4081,) 

```
Version is GNU Radio Companion 3.7.10 (installed through apt).

**Comment by marcusmueller** [comment]
Block is deprecated, and won't be fixed. Sorry! Closing this issue.

Thank you for understanding!
