### ISSUE TITLE
gr_modtool python tagged_stream block fails

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#2489]
Issue raised by Sebastian.  

gr_modtool consistently fails when trying to create a new tagged stream block of type python.  This is with master (3.8) branch.  Also, it forces you to enter valid argument list, but that looks to be a separate issue.
```

josh@josh-p51:~/gr-tmp$ gr_modtool add -t tagged_stream -l python foo
GNU Radio module name identified: tmp
Language: Python
Block/code identifier: foo
Please specify the copyright holder: 
Enter valid argument list, including default arguments: 

Enter valid argument list, including default arguments: 

Enter valid argument list, including default arguments: 
0
Add Python QA code? [Y/n] n
Adding file 'python/foo.py'...
Traceback (most recent call last):
  File "/share/gnuradio/grdev/bin/gr_modtool", line 30, in <module>
    cli()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/share/gnuradio/grdev/lib/python3.6/dist-packages/gnuradio/modtool/cli/base.py", line 149, in wrapper
    return func(*args, **kwargs)
  File "/share/gnuradio/grdev/lib/python3.6/dist-packages/gnuradio/modtool/cli/add.py", line 81, in cli
    run(self)
  File "/share/gnuradio/grdev/lib/python3.6/dist-packages/gnuradio/modtool/cli/base.py", line 168, in run
    module.run()
  File "/share/gnuradio/grdev/lib/python3.6/dist-packages/gnuradio/modtool/core/add.py", line 144, in run
    self._run_python()
  File "/share/gnuradio/grdev/lib/python3.6/dist-packages/gnuradio/modtool/core/add.py", line 275, in _run_python
    self._write_tpl('block_python', self.info['pydir'], fname_py)
  File "/share/gnuradio/grdev/lib/python3.6/dist-packages/gnuradio/modtool/core/add.py", line 125, in _write_tpl
    f.write(render_template(tpl, **self.info))
  File "/share/gnuradio/grdev/lib/python3.6/dist-packages/gnuradio/modtool/tools/code_generator.py", line 63, in render_template
    return tpl.render(**kwargs)
  File "/usr/lib/python3/dist-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7fc10008ac50", line 39, in render_body
KeyError: 'tagged_stream'
```

**Comment by mormj** [comment]
It looks like there is no code in place in modtool to handle tagged stream python blocks

```
Templates['block_python'] = '''#!/usr/bin/env python
# -*- coding: utf-8 -*-
${str_to_python_comment(license)}
<%
    if blocktype == 'noblock':
        return
    if blocktype in ('sync', 'sink', 'source'):
        parenttype = 'gr.sync_block'
    else:
        parenttype = {
            'hier': 'gr.hier_block2',
            'interpolator': 'gr.interp_block',
            'decimator': 'gr.decim_block',
            'general': 'gr.basic_block'
        }[blocktype]
%>
```
etc. 

So this functionality needs to be added into the templates

**Comment by mormj** [comment]
Ok, so tagged stream blocks are not implemented at all in modtool.  The short term fix is to add a better exception or warning message to flag this situation.  Long term it could be added, but is quite an invasive bit of work to add to the block gateways, etc.
