### ISSUE TITLE
gr_modtool error for tagged_stream block w/ Python (GR 3.7)

### ISSUE THREAD

**Issue by grosseman** [gnuradio/gnuradio#2492]
This is very similar to #2489 except the error is occurring for GR 3.7. The error is occuring both for gr_modtool installed with PyBOMBS (3.7.13) and as installed with apt under Ubuntu 18-04.2 (3.7.11). 

```
sebbe@sebbe-ThinkPad-E560:~/gr-test$ gr_modtool add -l python -t tagged_stream
GNU Radio module name identified: test
Language: Python
Enter name of block/code (without module name prefix): test
Block/code identifier: test
Enter valid argument list, including default arguments: 
Add Python QA code? [Y/n] n
Adding file 'python/test.py'...
Traceback (most recent call last):
  File "/usr/bin/gr_modtool", line 46, in <module>
    main()
  File "/usr/bin/gr_modtool", line 38, in main
    modtool.run()
  File "/usr/lib/python2.7/dist-packages/gnuradio/modtool/modtool_add.py", line 168, in run
    self._run_python()
  File "/usr/lib/python2.7/dist-packages/gnuradio/modtool/modtool_add.py", line 313, in _run_python
    self._write_tpl('block_python', self._info['pydir'], fname_py)
  File "/usr/lib/python2.7/dist-packages/gnuradio/modtool/modtool_add.py", line 154, in _write_tpl
    open(path_to_file, 'w').write(get_template(tpl, **self._info))
  File "/usr/lib/python2.7/dist-packages/gnuradio/modtool/code_generator.py", line 58, in get_template
    return str(GRMTemplate(Templates[tpl_id], searchList=kwargs))
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
    rc = getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1558365709_86_69673.py", line 99, in respond
KeyError: 'tagged_stream'
```

**Comment by mormj** [comment]
This has been "fixed" on 3.8 and master (3.9) by adding a warning
```
gnuradio.modtool.core.base.ModToolException: Tagged Stream Blocks for Python currently unsupported
```
