### ISSUE TITLE
GRC regression with commit dba48d0

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#2586]
This commit doesn't work properly if the freedesktop icon hasn't been installed. Instead of loading the built-in icon, you get an error.

Here's the error:
```
Traceback (most recent call last):
  File "/opt/gnuradio-3.7.12git/lib/python3.6/dist-packages/gnuradio/grc/gui/Application.py", line 101, in do_activate
    self.main_window = MainWindow(self, self.platform)
  File "/opt/gnuradio-3.7.12git/lib/python3.6/dist-packages/gnuradio/grc/gui/MainWindow.py", line 75, in __init__
    icon = icon_theme.load_icon("gnuradio-grc", 48, 0)
GLib.Error: gtk-icon-theme-error-quark: Icon 'gnuradio-grc' not present in theme ubuntu-mono-dark (0)
```

**Comment by dl1ksv** [comment]
Should be fixed with #2591
