### ISSUE TITLE
gr-blocks/file_meta_sink: Default extra_dict does not work

### ISSUE THREAD

**Issue by ThomasHabets** [gnuradio/gnuradio#2975]
Steps to reproduce:

1. Run at current master HEAD (12de35d23071fe957ed78078fcbda99d2fc38207)
1. In gnuradio-companion, instantiate a "File meta sink", and connect a source to it (e.g. a signal source)
1. Try to run it

## Expected results

Signal data to be written to the file.

## Actual results

```
Traceback (most recent call last):                                                                                                                            
  File "[…]/default2.py", line 130, in <module>                                                                  
    main()                                                                                                                                                    
  File "[…]/default2.py", line 108, in main                                                                      
    tb = top_block_cls()                                                                                                                                      
  File "[…]/default2.py", line 76, in __init__                                                                       self.blocks_file_meta_sink_0 = blocks.file_meta_sink(gr.sizeof_gr_complex*1, 'foo.dat', samp_rate, 1, blocks.GR_FILE_FLOAT, True, 1000000, {}, False)     
  File "[…]/opt/gnuradio/lib/python3.7/dist-packages/gnuradio/blocks/blocks_swig0.py", line 1234, in make                           
    return _blocks_swig0.file_meta_sink_make(*args, **kwargs)                                                                                                 
TypeError: in method 'file_meta_sink_make', argument 8 of type 'pmt::pmt_t'                                                                                   
 ```

## More notes

The default value for `extra_dict` is `""`, which doesn't seem to be parsed well. I can make it work by adding an import for `from gnuradio.gr import pmt` and putting `pmt.to_pmt({})` in `extra_dict`, but I shouldn't need to do that, right?

**Comment by ThomasHabets** [comment]
Oops, this is a dup of https://github.com/gnuradio/gnuradio/issues/2365
