### ISSUE TITLE
grc: open flowgraph fails `Error: 'EPyModule' object has no attribute 'cpp_templates'`

### ISSUE THREAD

**Issue by jdemel** [gnuradio/gnuradio#3269]
Most flowgraphs load perfectly fine. Though, recently I've seen the following error on multiple machines:
```
Loading: "[prefix]/src/gr-gfdm/examples/gfdm_ota_demo.grc"
Error: 'EPyModule' object has no attribute 'cpp_templates'
>>> Failure
Traceback (most recent call last):
  File "[pyprefix]/gnuradio/grc/gui/MainWindow.py", line 253, in new_page
    file_path=file_path,
  File "[pyprefix]/gnuradio/grc/gui/Notebook.py", line 96, in __init__
    flow_graph.import_data(initial_state)
  File "[pyprefix]/gnuradio/grc/core/FlowGraph.py", line 408, in import_data
    self.new_block(block_id) or
  File "[pyprefix]/gnuradio/grc/core/FlowGraph.py", line 300, in new_block
    block = self.parent_platform.make_block(self, block_id, **kwargs)
  File "[pyprefix]/gnuradio/grc/core/platform.py", line 418, in make_block
    return cls(parent, **kwargs)
  File "[pyprefix]/gnuradio/grc/gui/canvas/block.py", line 35, in __init__
    super(self.__class__, self).__init__(parent, **n)
  File "[pyprefix]/gnuradio/grc/core/blocks/block.py", line 81, in __init__
    self.orig_cpp_templates = self.cpp_templates # The original template, in case we have to edit it when transpiling to C++
AttributeError: 'EPyModule' object has no attribute 'cpp_templates'
```
It happens with the shown flowgraph from gr-gfdm. But I've seen it in other places too. Since I can't open the flowgraph anymore, it's hard to guess why this happens.

This happens on Ubuntu 18.04 with GNU Radio on master branch at commit `edaa88fbc889a3d09fd374c3eb49cd46174b049f`.

**Comment by jdemel** [comment]
I just saw #3261. Apparently, this issue is a duplicate of #3260 . Thus, I'm closing it again.
