### ISSUE TITLE
qa_pmt: uses from_long, expects 64 bit, even on 32 bit ARM

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#3326]
According to @drmpeg [here](https://github.com/gnuradio/gnuradio/pull/3320#pullrequestreview-390489362), 

> Unfortunately, qa_pmt always fails on 32-bit systems because it's using from_long to test for 64-bit numbers. But that's a side issue.

Let's make it a proper issue here.

**Comment by drmpeg** [comment]
Here's the error dump.
```
ctest -V -R qa_pmt
UpdateCTestConfiguration  from :/home/ubuntu/xfer/gnuradio/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/ubuntu/xfer/gnuradio/build/DartConfiguration.tcl
Test project /home/ubuntu/xfer/gnuradio/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 155
    Start 155: qa_pmt

155: Test command: /bin/sh "/home/ubuntu/xfer/gnuradio/build/gnuradio-runtime/python/pmt/qa_pmt_test.sh"
155: Test timeout computed to be: 10000000
155: ..............E..E.
155: ======================================================================
155: ERROR: test15 (__main__.test_pmt)
155: ----------------------------------------------------------------------
155: Traceback (most recent call last):
155:   File "/home/ubuntu/xfer/gnuradio/gnuradio-runtime/python/pmt/qa_pmt.py", line 116, in test15
155:     x_pmt = pmt.from_long(const)
155:   File "/home/ubuntu/xfer/gnuradio/build/gnuradio-runtime/python/pmt/../../swig/pmt_swig.py", line 1942, in from_long
155:     return _pmt_swig.from_long(x)
155: OverflowError: in method 'from_long', argument 1 of type 'long'
155: 
155: ======================================================================
155: ERROR: test18 (__main__.test_pmt)
155: ----------------------------------------------------------------------
155: Traceback (most recent call last):
155:   File "/home/ubuntu/xfer/gnuradio/gnuradio-runtime/python/pmt/qa_pmt.py", line 141, in test18
155:     x_pmt = pmt.from_long(const)
155:   File "/home/ubuntu/xfer/gnuradio/build/gnuradio-runtime/python/pmt/../../swig/pmt_swig.py", line 1942, in from_long
155:     return _pmt_swig.from_long(x)
155: OverflowError: in method 'from_long', argument 1 of type 'long'
155: 
155: ----------------------------------------------------------------------
155: Ran 19 tests in 0.021s
155: 
155: FAILED (errors=2)
155: ((a . 123765))
1/2 Test #155: qa_pmt ...........................***Failed    1.14 sec
test 156
    Start 156: qa_pmt_to_python

156: Test command: /bin/sh "/home/ubuntu/xfer/gnuradio/build/gnuradio-runtime/python/pmt/qa_pmt_to_python_test.sh"
156: Test timeout computed to be: 10000000
156: ..
156: ----------------------------------------------------------------------
156: Ran 2 tests in 0.002s
156: 
156: OK
2/2 Test #156: qa_pmt_to_python .................   Passed    0.47 sec

The following tests passed:
	qa_pmt_to_python

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   2.04 sec

The following tests FAILED:
	155 - qa_pmt (Failed)
Errors while running CTest
```
