### ISSUE TITLE
GRC: Many parameter block errors when trying to load gr-uhd/examples/grc/uhd_fft.grc

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#3477]
This is on latest master with the patch from https://github.com/gnuradio/gnuradio/pull/3464
```
ubuntu@arm:~/xfer$ gnuradio-companion uhd_fft.grc
<<< Welcome to GNU Radio Companion 3.9.0.0-git >>>

Block paths:
	/opt/gnuradio-3.9.0git/share/gnuradio/grc/blocks

Loading: "/home/ubuntu/xfer/uhd_fft.grc"
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block antenna
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 1, in <module>
NameError: name 'RX2' is not defined
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block args
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block spec
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block stream_args
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block wire_format
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block antenna
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 1, in <module>
NameError: name 'RX2' is not defined
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block args
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block spec
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block stream_args
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block wire_format
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
>>> Done
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block antenna
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 1, in <module>
NameError: name 'RX2' is not defined
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block args
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block spec
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block stream_args
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block wire_format
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block antenna
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 1, in <module>
NameError: name 'RX2' is not defined
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block args
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block spec
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block stream_args
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block wire_format
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block antenna
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 1, in <module>
NameError: name 'RX2' is not defined
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block args
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block spec
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block stream_args
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block wire_format
Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by drmpeg** [comment]
Can be fixed with quotes in the Value field.
