### ISSUE TITLE
In-tree examples that fail to compile

### ISSUE THREAD

**Issue by mormj** [gnuradio/gnuradio#3534]
The following examples cause an exception when being compiled by grcc and need to be investigated

- [ ] gr-trellis/examples/grc/pccc.grc
- [ ] gr-trellis/examples/grc/sccc.grc 
- [ ] gr-trellis/examples/grc/viterbi_equalization.grc 
- [ ] gr-trellis/examples/grc/turbo_equalization.grc 
- [ ] gr-trellis/examples/grc/tcm.grc
- [ ] gr-trellis/examples/grc/interference_cancellation.grc
- [x] gr-fec/examples/tpc_ber_curve_gen.grc 
- [ ] gr-fec/examples/fecapi_async_ldpc_encoders.grc 
- [ ] gr-fec/examples/fecapi_tagged_decoders.grc

**Comment by mormj** [comment]
The trellis examples are also covered under #2529

**Comment by mcdiarmid** [comment]
Perhaps related as I have been going through examples to figure out how to use the trellis blocks - it appears that some of the trellis blocks either have no python binding, or have a naming mis-match between the flowgraph block and python binding library.  For example:

```bash
/usr/bin/python3 -u /home/mcdiarmid/Documents/GNURadio Examples/viterbi_equalization.py

Traceback (most recent call last):
  File "/home/mcdiarmid/Documents/GNURadio Examples/viterbi_equalization.py", line 300, in <module>
    main()
  File "/home/mcdiarmid/Documents/GNURadio Examples/viterbi_equalization.py", line 276, in main
    tb = top_block_cls()
  File "/home/mcdiarmid/Documents/GNURadio Examples/viterbi_equalization.py", line 98, in __init__
    self.trellis_viterbi_combined_xx_0 = trellis.viterbi_combined_fb(trellis.fsm(fsm), block//bpsym, -1, -1, tot_mod[0], tot_mod[1], digital.TRELLIS_EUCLIDEAN)
AttributeError: module 'gnuradio.trellis' has no attribute 'viterbi_combined_fb'
```

```python
>>> from gnuradio import trellis
>>> dir(trellis)
['TRELLIS_MIN_SUM', 'TRELLIS_SUM_PRODUCT', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'constellation_metrics_cf', 'encoder_bb', 'encoder_bi', 'encoder_bs', 'encoder_ii', 'encoder_si', 'encoder_ss', 'fsm', 'interleaver', 'os', 'permutation', 'siso_combined_f', 'siso_f', 'siso_type_t', 'trellis_python', 'viterbi_b', 'viterbi_i', 'viterbi_s']
```

Side-note: would love an example with an explanation and/or diagram describing how a trellis maps to a .fsm file, and consequently how to use it with the GNURadio blocks.

**Comment by mormj** [comment]
As of commit a7dbb78743964e434eef9b2582c56c0f84d70759 on master, grcc can be run on all example files using  `python3 -B -m pytest /path/to/gnuradio/grc/tests -m "examples"` and produce a bunch of output.  Right now, there are 49 failing tests:
```
FAILED ../grc/tests/test_examples.py::test_all_examples[example21] - AssertionError: ('tpc_ber_curve_gen.grc', ['fec_bercurve_generator_0 - Source - bus0#32(32): Port is not connected.', 'fec_bercurve_ge...ce - bus0#32(32): Port is not connected.', 'qtgui_bercu...
FAILED ../grc/tests/test_examples.py::test_all_examples[example26] - AssertionError: ('uhd_msg_tune.grc', ['qtgui_freq_sink_x_0 - Sink - in(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example27] - AssertionError: ('uhd_wbfm_receive.grc', ['low_pass_filter_0 - Sink - in(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example28] - AssertionError: ('uhd_const_wave.grc', ['analog_const_source_x_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example29] - AssertionError: ('uhd_two_tone_loopback.grc', ['blocks_add_xx - Source - out(0): Port is not connected.', 'qtgui_freq_sink_x_0 - Sink - in(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example30] - AssertionError: ('uhd_normalized_gain.grc', ['blocks_null_sink_0 - Sink - in(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example31] - AssertionError: ('uhd_fft.grc', ['qtgui_freq_sink_x_0 - Sink - in(0): Port is not connected.', 'qtgui_time_sink_x_0 - Sink - in(0): Port is not connected.', 'qtgui_waterfall_sink_x_0 - Sink - ...
FAILED ../grc/tests/test_examples.py::test_all_examples[example48] - AttributeError: 'FlowGraph' object has no attribute 'name'
FAILED ../grc/tests/test_examples.py::test_all_examples[example101] - AssertionError: ('USRP_FM_stereo.grc', ['filter_fft_low_pass_filter_0 - Sink - in(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example121] - AssertionError: ('interference_cancellation.grc', ['qtgui_number_sink_0 - Sink - in(0): Port is not connected.', 'qtgui_number_sink_0_...e(eval(""" fsm_args """[1:-1], locals(),globals()), st...
FAILED ../grc/tests/test_examples.py::test_all_examples[example122] - AssertionError: ('viterbi_equalization.grc', ["analog_noise_source_x_0 - Param - Amplitude(amp): Expression None is invalid for type '...", "digital_chunks_to_symbols_xx_0_0 - Param - Dimensi...
FAILED ../grc/tests/test_examples.py::test_all_examples[example123] - AssertionError: ('sccc.grc', ["analog_noise_source_x_0 - Param - Amplitude(amp): Expression None is invalid for type 'real'.", "digita...sccc_decoder_combined_xx_0 - Param - Constellation(tab...
FAILED ../grc/tests/test_examples.py::test_all_examples[example124] - AssertionError: ('turbo_equalization.grc', ["analog_noise_source_x_0 - Param - Amplitude(amp): Expression None is invalid for type 're...lid for type 'int'.", "blocks_unpack_k_bits_bb_0_0_0 -...
FAILED ../grc/tests/test_examples.py::test_all_examples[example125] - AssertionError: ('pccc.grc', ["analog_noise_source_x_0 - Param - Amplitude(amp): Expression None is invalid for type 'real'.", "digita...pccc_decoder_combined_xx_0 - Param - Constellation(tab...
FAILED ../grc/tests/test_examples.py::test_all_examples[example126] - AssertionError: ('tcm.grc', ["analog_noise_source_x_0 - Param - Amplitude(amp): Expression None is invalid for type 'real'.", "digital...e(eval(""" fsm_args """[1:-1], locals(),globals()), st...
FAILED ../grc/tests/test_examples.py::test_all_examples[example127] - AssertionError: ('vv034-dtg016.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example128] - AssertionError: ('vv035-dtg052.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example129] - AssertionError: ('vv012-64qam45.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example130] - AssertionError: ('vv003-cr23.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example131] - AssertionError: ('uhd_atsc_rx.grc', ['blocks_file_sink_0 - Sink - in(0): Port is not connected.', 'dc_blocker_xx_0 - Sink - in(0): Por...d_0 - Sink - in(0): Port is not connected.', 'dtv_atsc...
FAILED ../grc/tests/test_examples.py::test_all_examples[example132] - AssertionError: ('vv013-64qam56.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example137] - AssertionError: ('vv016-256qam34.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example138] - AssertionError: ('vv004-8kfft.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example139] - AssertionError: ('vv009-4kfft.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example140] - AssertionError: ('vv036-dtg091.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example141] - AssertionError: ('vv017-paprtr.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example142] - AssertionError: ('vv008-16kfft.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example143] - AssertionError: ('vv007-16kfft.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example144] - AssertionError: ('uhd_atsc_capture.grc', ['blocks_file_sink_0 - Sink - in(0): Port is not connected.', 'usrp_freq_sink - Sink - in(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example145] - AssertionError: ('germany-g2.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example147] - AssertionError: ('germany-g4.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example148] - AssertionError: ('vv005-8kfft.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example149] - AssertionError: ('germany-g5.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example150] - AssertionError: ('germany-g1.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example151] - AssertionError: ('vv011-1kfft.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example152] - AssertionError: ('vv014-64qam34.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example155] - AssertionError: ('germany-g10.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example156] - AssertionError: ('vv015-8kfft.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example157] - AssertionError: ('germany-g9.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example159] - AssertionError: ('vv001-cr35.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example160] - AssertionError: ('germany-g6.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example161] - AssertionError: ('vv018-miso.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.', 'blocks_multiply_const_xx_0_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example162] - AssertionError: ('vv010-2kfft.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example163] - AssertionError: ('germany-g8.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example164] - AssertionError: ('germany-g7.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example165] - AssertionError: ('dvbt_tx_2k.grc', ['digital_ofdm_cyclic_prefixer_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example166] - AssertionError: ('dvbt_tx_8k.grc', ['digital_ofdm_cyclic_prefixer_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example167] - AssertionError: ('germany-g3.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
FAILED ../grc/tests/test_examples.py::test_all_examples[example168] - AssertionError: ('vv019-norot.grc', ['blocks_multiply_const_xx_0 - Source - out(0): Port is not connected.'])
```

**Comment by dkozel** [comment]
In chatting with @drmpeg a possible common cause for many of these failures could be that the blocks connect to USRP blocks. @mormj do you have gr-uhd enabled in your local build?

If the lack of USRP blocks is the root cause it would be a good enhancement to find a way for the Assertion to first check if there *is* a connection, but to a missing block and to print a better message that includes the missing block type/ID.

**Comment by drmpeg** [comment]
Having a UHD enabled build doesn't help. Maybe a solution would be to replace all UHD sinks and sources with gr-soapy blocks. After all, having UHD sinks and sources in examples isn't useful for many users.

**Comment by drmpeg** [comment]
Using a gr-soapy sink (I tried the bladeRF sink) works. However, it's not clear which sink should be used. I thought that maybe the custom sink might be a good choice, but it has a problem. See https://github.com/gnuradio/gnuradio/issues/4656

**Comment by dkozel** [comment]
Why doesn't having UHD enabled help? These are flowgraphs that work within GRC (right?) so why not through grcc?

As a side note, this PR might? improve the error messages?
https://github.com/gnuradio/gnuradio/pull/4674

**Comment by drmpeg** [comment]
I'm not seeing the ```demo_``` flow graphs in gr-channels failing here. So my count is 17.

Be aware that many flow graphs in gr-digital are being skipped. See https://github.com/gnuradio/gnuradio/issues/4976

**Comment by mormj** [comment]
> Do you know what `collected 213 items / 38 deselected / 175 selected` means? What's being deselected? Is there some blacklist? I can't find it.

Not sure what this means - probably a pytest thing??

> 
> `find . -name *.grc | wc` reports 237 .grc files, so there's more to test.
> 
> I really believe this flow graph testing should all be sorted out. It would definitely find regressions in pull requests.

Agreed - it would get us a long way to know when examples break


I have to look into the other failures.  I have codec2 installed

**Comment by argilo** [comment]
The UHD examples look fine. The tests pass if `test_examples.py` is changed like so:
```diff
--- a/grc/tests/test_examples.py
+++ b/grc/tests/test_examples.py
@@ -14,7 +14,10 @@ except FileExistsError:
 # Gather blocks
 BLOCK_PATHS = []
 ROOT = path.join(path.dirname(__file__), '../..')
-BLOCK_PATHS = [path.join(path.dirname(__file__), '../../grc/blocks'), '../../build/gr-uhd/grc']
+BLOCK_PATHS = [
+    path.join(path.dirname(__file__), '../../grc/blocks'),
+    path.join(path.dirname(__file__), '../../build/gr-uhd/grc'),
+]
 for file_dir in os.scandir(ROOT):
     # If it is a module
     if path.isdir(file_dir) and file_dir.name.startswith("gr-"):
```

**Comment by drmpeg** [comment]
@argilo, There's a PR that fixes all of this. See https://github.com/gnuradio/gnuradio/pull/5188

Unfortunately, although it works perfectly on a regular host. the CI fails miserably (and that's why the PR hasn't been merged).

**Comment by argilo** [comment]
Oh thanks, I missed that. I had stumbled across `test_examples.py` and started playing without knowing what was going on with it. :smile:

**Comment by marcusmueller** [comment]
after #5188 has been merged, tpc_ber_curve_gen still errors out when manually opened in GRC:

Properties of the QT GUI Bercurve Sink:

```
Param - Bus_Structure_Sink(bus_structure_sink):
	Value "list(map(lambda b:list(map(lambda a:b * len(esno) * 2 + a, range(len(esno)*2))), range(num_curves)))" cannot be evaluated:
	name 'num_curves' is not defined
```
