### ISSUE TITLE
GRC fails to start if GTK theme name not set

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#3723]
When trying to start a vanilla 3.8.2.0 (on f32 / cinnamon / awesome-wm, i.e. not on Gnome)
```
Traceback (most recent call last):
  File "/usr/bin/gnuradio-companion", line 102, in <module>
    run_main()
  File "/usr/bin/gnuradio-companion", line 95, in run_main
    exit(main())
  File "/usr/lib64/python3.8/site-packages/gnuradio/grc/main.py", line 73, in main
    from .gui.Platform import Platform
  File "/usr/lib64/python3.8/site-packages/gnuradio/grc/gui/Platform.py", line 26, in <module>
    from . import canvas
  File "/usr/lib64/python3.8/site-packages/gnuradio/grc/gui/canvas/__init__.py", line 21, in <module>
    from .param import Param
  File "/usr/lib64/python3.8/site-packages/gnuradio/grc/gui/canvas/param.py", line 23, in <module>
    from .. import ParamWidgets, Utils, Constants
  File "/usr/lib64/python3.8/site-packages/gnuradio/grc/gui/ParamWidgets.py", line 66, in <module>
    add_style_provider()
  File "/usr/lib64/python3.8/site-packages/gnuradio/grc/gui/ParamWidgets.py", line 58, in add_style_provider
    dark_theme = have_dark_theme()
  File "/usr/lib64/python3.8/site-packages/gnuradio/grc/gui/ParamWidgets.py", line 47, in have_dark_theme
    return is_dark_theme(theme_name)
  File "/usr/lib64/python3.8/site-packages/gnuradio/grc/gui/ParamWidgets.py", line 38, in is_dark_theme
    return theme_name in Constants.GTK_DARK_THEMES or "dark" in theme_name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by marcusmueller** [comment]
Fixed by #3724
