### ISSUE TITLE
WBFM_Transmit incompatible constructor arguments

### ISSUE THREAD

**Issue by duggabe** [gnuradio/gnuradio#3919]
Ubuntu 20.04.1
GR/GRC 3.9.0.0-git built from source 26 Aug 2020

```
Executing: /usr/bin/python3 -u /home/barry/GRdev/wbfm_demo.py

len(interp_taps) = 244
Traceback (most recent call last):
  File "/home/barry/GRdev/wbfm_demo.py", line 174, in <module>
    main()
  File "/home/barry/GRdev/wbfm_demo.py", line 150, in main
    tb = top_block_cls()
  File "/home/barry/GRdev/wbfm_demo.py", line 100, in __init__
    self.analog_wfm_tx_0 = analog.wfm_tx(
  File "/usr/local/lib/python3/dist-packages/gnuradio/analog/wfm_tx.py", line 61, in __init__
    self.interpolator = filter.interp_fir_filter_fff (interp_factor, interp_taps)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. gnuradio.filter.filter_python.interp_fir_filter_fff(interpolation: int, taps: List[float])

Invoked with: 4.0, [0.0114326689627949, -0.010485003783906068, -0.005653762862842927, -0.0021968526560863324, 0.00022313136838484417, 0.0017888663494369183, 0.002561612467677594, 0.0025607145911772126, 0.0018506930877974198, 
...
.0025607145911772126, 0.002561612467677594, 0.0017888663494369183, 0.00022313136838484417, -0.0021968526560863324, -0.005653762862842927, -0.010485003783906068, 0.0114326689627949]
```
At line 52 of https://github.com/gnuradio/gnuradio/blob/master/gr-analog/python/analog/wfm_tx.py
`interp_factor = quad_rate / audio_rate`
produced '4.0' instead of '4' even though both factors were integers.

This is the same problem for WBFM as https://github.com/gnuradio/gnuradio/issues/3651 addressed for NBFM

**Comment by marcusmueller** [comment]
Ah, the good old Python2->Python3 division operator problem: Under Python 2, `3/4` means integer division and yields 0, under Python3 it yields 0.75. If you want to have integer division, use `//`; that should work under Python2.7, too, by the way.
