### ISSUE TITLE
Drag-and-drop of block to canvas throws exception on macOS

### ISSUE THREAD

**Issue by rgov** [gnuradio/gnuradio#3979]
On macOS Big Sur, with Python 3.9 and GNU Radio 3.8 installed via Homebrew:

When I try to drag a block onto the GNU Radio Companion canvas, an exception is thrown:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/gnuradio/3.8.2.0_5/lib/python3.9/site-packages/gnuradio/grc/gui/DrawingArea.py", line 103, in _handle_drag_data_received
    self._flow_graph.add_new_block(selection_data.get_text(), coords)
  File "/usr/local/Cellar/gnuradio/3.8.2.0_5/lib/python3.9/site-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 176, in add_new_block
    block.coordinate = coor
AttributeError: 'NoneType' object has no attribute 'coordinate'
```

Double clicking on a block to add it to the canvas does work, though.

**Comment by rgov** [comment]
It seems to be that when performing drag and drop, the `key` parameter passed to `FlowGraph.add_new_block` is `None`. The `Gtk.SelectionData` object in the drag handler does not seem to contain any data.

If I drop some random thing onto the canvas, then I do see that the `Gtk.SelectionData` is populated. So perhaps on the origin side of the drag, the data is not being set properly?

**Comment by rgov** [comment]
I added some debug statements to `BlockTreeWindow._handle_drag_get_data`:

```
print('setting selection_data to', key)
selection_data.set_text(key, len(key))
print('it is now set to', selection_data.get_text())
```

It outputs:

```
setting selection_data to blocks_message_debug
it is now set to None
```

**Comment by rgov** [comment]
Found this previous discussion from @eblot: https://discourse.gnome.org/t/question-related-to-setting-up-text-drag-and-drop-pygtk3/1542

The proposal is to change

```diff
-DND_TARGETS = [('STRING', Gtk.TargetFlags.SAME_APP, 0)]
+DND_TARGETS = [('UTF8_STRING', Gtk.TargetFlags.SAME_APP, 0)]
```

which seems to work.

**Comment by rgov** [comment]
Closing as duplicate of #2727.
