### ISSUE TITLE
Deriving OOT header format from header_format_base

### ISSUE THREAD

**Issue by nslogan** [gnuradio/gnuradio#4156]
## Key Question

How should a header format be derived from `header_format_base`? It seems there are build dependencies / swig configuration needed but there is no OOT module example (that I have found).

## Environment

- GNU Radio version: 3.8.2.0
- Python version: 3.6.9

## Background

I'm trying to derive an OOT header format from `header_format_base` per the [API documentation](https://www.gnuradio.org/doc/doxygen/classgr_1_1digital_1_1header__format__base.html). I have successfully built a skeleton that compiles and prints to the console whenever certain methods are called (for testing) but receive errors when executing a flow graph.

The key pieces of python from the flow graph:

```python
# ... snip ...
h = logan.header_format_test()
# ... snip ...
digital.protocol_formatter_async(h)
# ... snip ...
```
Below is the output at the terminal when executing the flow graph:
```
python3 packet.py 
Warning: failed to XInitThreads()
CALLED
CONSTRUCTOR
Traceback (most recent call last):
  File "../../dev/packet.py", line 229, in <module>
    main()
  File "../../dev/packet.py", line 205, in main
    tb = top_block_cls()
  File "../../dev/packet.py", line 133, in __init__
    self.digital_protocol_formatter_async_0 = digital.protocol_formatter_async(hdr_format)
  File "/usr/lib/python3/dist-packages/gnuradio/digital/digital_swig2.py", line 1890, in make
    return _digital_swig2.protocol_formatter_async_make(format)
TypeError: in method 'protocol_formatter_async_make', argument 1 of type 'gr::digital::header_format_base::sptr const &'
swig/python detected a memory leak of type 'gr::logan::header_format_test::sptr *', no destructor found.
```

It seems there are two concurrent issues:

- Lack of destructor from swig: `swig/python detected a memory leak of type 'gr::logan::header_format_test::sptr *', no destructor found.`
    + This can be tested in a python session by importing my module, `logan`, executing `h = logan.header_format_test()` and then exiting the session - the memory leak detection will trigger
- The TypeError generated by the call to `_digital_swig2.protocol_formatter_async_make(format)`: `TypeError: in method 'protocol_formatter_async_make', argument 1 of type 'gr::digital::header_format_base::sptr const &'`

## Files

I've stripped out comments and extra space so these are a bit more readable.

### header_format_test.h

```c++
#ifndef INCLUDED_LOGAN_HEADER_FORMAT_TEST_H
#define INCLUDED_LOGAN_HEADER_FORMAT_TEST_H

#include <logan/api.h>
#include <gnuradio/digital/header_format_default.h>

namespace gr {
namespace logan {

class LOGAN_API header_format_test : public digital::header_format_base
{
public:
    typedef std::shared_ptr<header_format_test> sptr;

    header_format_test();
    virtual ~header_format_test();

    bool format(int nbytes_in,
            const unsigned char* input,
            pmt::pmt_t& output,
            pmt::pmt_t& info) override;

    bool parse(int nbits_in,
               const unsigned char* input,
               std::vector<pmt::pmt_t>& info,
               int& nbits_processed) override;

    size_t header_nbits() const override;

    static sptr make();

protected:
    bool header_ok() override;
    int header_payload() override;
};

} // namespace logan
} // namespace gr

#endif /* INCLUDED_LOGAN_HEADER_FORMAT_TEST_H */
```

### header_format_test.cc

```c++
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <gnuradio/digital/header_buffer.h>
#include <logan/header_format_test.h>
#include <gnuradio/io_signature.h>
#include <iostream>

namespace gr {
namespace logan {

header_format_test::sptr header_format_test::make() {
    std::cout << "CALLED" << std::endl;
    return header_format_test::sptr(new header_format_test());
}

header_format_test::header_format_test()
    : header_format_base() {
    std::cout << "CONSTRUCTOR" << std::endl;
}

header_format_test::~header_format_test() {}

bool header_format_test::format(int nbytes_in,
        const unsigned char* input,
        pmt::pmt_t& output,
        pmt::pmt_t& info) {
    std::cout << "CALL: format" << std::endl;
    return true;
}

bool header_format_test::parse(int nbits_in,
           const unsigned char* input,
           std::vector<pmt::pmt_t>& info,
           int& nbits_processed) {
    std::cout << "CALL: parse" << std::endl;
    return true;
}

size_t header_format_test::header_nbits() const {
    std::cout << "CALL: header_nbits" << std::endl;
    return 0;
}

bool header_format_test::header_ok() {
    return true;
}

int header_format_test::header_payload() {
    return 0;
}

} /* namespace logan */
} /* namespace gr */
```

### logan_swig.i

```swig
/* -*- c++ -*- */

#define LOGAN_API

%include "gnuradio.i"           // the common stuff
%include "digital_swig2.i"

//load generated python docstrings
%include "logan_swig_doc.i"

%{
#include "logan/header_format_test.h"
%}

%include "logan/header_format_test.h"

%template(header_format_test_sptr) boost::shared_ptr<gr::logan::header_format_test>;
%pythoncode %{
header_format_test_sptr.__repr__ = lambda self: "<header_format_test>"
header_format_test = header_format_test .make;
%}
```
### gr-logan/swig/CMakeLists.txt

**NOTE:** I've only included the portion of the cmake file that's relevant to `GR_SWIG_MAKE`, the rest is the boilerplate from `gr_modtool`.

```cmake
set(GR_SWIG_INCLUDE_DIRS
	$<TARGET_PROPERTY:gnuradio::runtime_swig,INTERFACE_INCLUDE_DIRECTORIES>
	$<TARGET_PROPERTY:gnuradio::gnuradio-digital,INTERFACE_INCLUDE_DIRECTORIES>
)
set(GR_SWIG_TARGET_DEPS gnuradio::runtime_swig)

set(GR_SWIG_LIBRARIES gnuradio-logan gnuradio::gnuradio-digital)

set(GR_SWIG_DOC_FILE ${CMAKE_CURRENT_BINARY_DIR}/logan_swig_doc.i)
set(GR_SWIG_DOC_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/../include)

GR_SWIG_MAKE(logan_swig logan_swig.i)
```

**Comment by nslogan** [comment]
I have found the issue, my *.h/*.cc files were based on the 3.9 tree before I switched to the 3.8 tree after realizing there had been a transition from SWIG to Pybind11. In the older files there is no local typedef of `sptr`, but rather the `header_format_base::sptr` typedef is used. Commenting out my typedef fixed the issue. I also updated my SWIG template to not depend on the full `digital_swig2.i` but rather only include the necessary headers.

```swig
#define LOGAN_API

#define DIGITAL_API


%include "gnuradio.i"           // the common stuff

//load generated python docstrings
%include "logan_swig_doc.i"

%{
#include <gnuradio/digital/header_format_base.h>
#include <gnuradio/digital/header_format_default.h>

#include "logan/header_format_test.h"
%}

%include <gnuradio/digital/header_format_base.h>
%include <gnuradio/digital/header_format_default.h>

%include "logan/header_format_test.h"

%template(header_format_test_sptr) boost::shared_ptr<gr::logan::header_format_test>;
%pythoncode %{
header_format_test_sptr.__repr__ = lambda self: "<header_format_test>"
header_format_test = header_format_test .make;
%}
```
