### ISSUE TITLE
GRC: warnings-to-errors leads to non-starting GRC on Fedora 35

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#5216]
### What happened?

https://bugzilla.redhat.com/show_bug.cgi?id=2014797

A user says that the Gtk module loader warning causes a python traceback – which we cause by setting all warnings to be errors when starting GRC: 

https://github.com/gnuradio/gnuradio/blob/1a0be2e6b54496a8136a64d86e372ab219c6559b/grc/scripts/gnuradio-companion#L47

Related: https://github.com/gnuradio/gnuradio/issues/4891 which also happens because something with setting `filterwarnings("error")` breaks loading Gtk, seemingly.

### System Information

OS: Fedora 35
GR Installation Method: native distro packages

### GNU Radio Version

3.9 (maint-3.9)

### Specific Version

3.9.2.0

### Steps to Reproduce the Problem

`gnuradio-companion`

### Relevant log output

```shell
$ gnuradio-companion 
Traceback (most recent call last):
  File "/usr/bin/gnuradio-companion", line 53, in check_gtk
    from gi.repository import Gtk
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gnuradio-companion", line 90, in <module>
    check_gtk()
  File "/usr/bin/gnuradio-companion", line 57, in check_gtk
    die(err, "Failed to initialize GTK. If you are running over ssh, "
  File "/usr/bin/gnuradio-companion", line 32, in die
    from gi.repository import Gtk
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()
```

**Comment by marcusmueller** [comment]
(can reproduce in podman/docker)
