### ISSUE TITLE
digital: Constellation object can't generate C++ object because of Python `value` in yml

### ISSUE THREAD

**Issue by ThomasHabets** [gnuradio/gnuradio#5492]
### What happened?

Creating a flow graph in GRC with C++ code generation fails. When trying to generate the code:

```
Generating: '/…/test_cpp'
Generate Error: 'value'
>>> Failure
Traceback (most recent call last):
  File "/…/opt/gnuradio-3.10.0.0-rc4/lib/python3.9/site-packages/gnuradio/grc/gui/Application.py", line 737, in _handle_action
    generator.write()
  File "/…/opt/gnuradio-3.10.0.0-rc4/lib/python3.9/site-packages/gnuradio/grc/core/generator/cpp_top_block.py", line 86, in write
    self._variable_types()
  File "/…/opt/gnuradio-3.10.0.0-rc4/lib/python3.9/site-packages/gnuradio/grc/core/generator/cpp_top_block.py", line 310, in _variable_types
    if var.params['value'].dtype != 'raw':
KeyError: 'value'
```

Also note that the error seen inside GRC is not great. There you just see:
```
Generating: '/…/tmp/test_cpp/test_cpp'
Generate Error: 'value'
>>> Failure
```

Commenting out the `value: ` line in `/…/opt/gnuradio-3.10.0.0-rc4/share/gnuradio/grc/blocks/digital_constellation.block.yml` makes that block's code generation work, but it seems that the Constellation Encoder requires `value`, so it's not a fix.

### System Information

OS: Linux
GR Installation Method: Source

### GNU Radio Version

3.10-git (master)

### Specific Version

3.10.0.0-rc4

### Steps to Reproduce the Problem

1. Open grc
2. Add a `Constellation Object`
3. Open the root block
4. Set C++ code generation
5. Set an ID, because you have to
6. Press the code generation or run buttons
7. Get error message. (check the actual console for full info, GRC bottom left only shows part of it)

### Relevant log output

```shell
Generating: '/…/test_cpp'
Generate Error: 'value'
>>> Failure
Traceback (most recent call last):
  File "/…/opt/gnuradio-3.10.0.0-rc4/lib/python3.9/site-packages/gnuradio/grc/gui/Application.py", line 737, in _handle_action
    generator.write()
  File "/…/opt/gnuradio-3.10.0.0-rc4/lib/python3.9/site-packages/gnuradio/grc/core/generator/cpp_top_block.py", line 86, in write
    self._variable_types()
  File "/…/opt/gnuradio-3.10.0.0-rc4/lib/python3.9/site-packages/gnuradio/grc/core/generator/cpp_top_block.py", line 310, in _variable_types
    if var.params['value'].dtype != 'raw':
KeyError: 'value'
```

**Comment by mormj** [comment]
Looks like this was previously reported here: https://github.com/gnuradio/gnuradio/issues/5090
