### ISSUE TITLE
GNU radio File Source Begin tag issue

### ISSUE THREAD

**Issue by raam96** [gnuradio/gnuradio#5586]
Executing: C:\Users\npraa\AppData\Local\Programs\Python\Python39\python.exe -u C:\Users\npraa\Desktop\Raam.py

Traceback (most recent call last):
  File "C:\Users\npraa\Desktop\Raam.py", line 187, in <module>
    main()
  File "C:\Users\npraa\Desktop\Raam.py", line 165, in main
    tb = top_block_cls()
  File "C:\Users\npraa\Desktop\Raam.py", line 114, in __init__
    self.blocks_file_source_0.set_begin_tag({})
TypeError: set_begin_tag(): incompatible function arguments. The following argument types are supported:
    1. (self: gnuradio.blocks.blocks_python.file_source, val: pmt.pmt_python.pmt_base) -> None

Invoked with: <gnuradio.blocks.blocks_python.file_source object at 0x0000027B60C32DF0>, {}

**Comment by raam96** [comment]
![Capture](https://user-images.githubusercontent.com/84164103/154811090-517cf130-5ead-4545-8eac-44e8bf7f6c2b.PNG)
Im Getting this issue , i dont know what to do. Where is the issue can anyone help me. Problem is with the file source

**Comment by raam96** [comment]
![Uploading Capture2.PNG…]()

**Comment by raam96** [comment]
![Capture2](https://user-images.githubusercontent.com/84164103/154811145-c8cf566d-0419-4235-b6e8-275562cff906.PNG)

**Comment by raam96** [comment]
thank you for that... brother . that issue has been ok but the new issue is being raised. \\\\\\\\\\

gr::log :WARN: file_source0 - file size is not a multiple of item size
gr::log :ERROR: pagesize - no info; setting pagesize = 4096
gr::log :FATAL: tagged_stream_to_pdu0 - Missing a required length tag on port 0 at item #0
gr::log :ERROR: thread_body_wrapper - ERROR thread[thread-per-block[3]: <block tagged_stream_to_pdu(2)>]: Missing length tag.

**Comment by raam96** [comment]
> @raam96 - It looks like the block doesn't know how to interpret `{}` as a valid pmt tag. What happens when you set the "Add begin tag" field to `pmt.PMT_NIL` which is the grc default
> 
> Also, general support questions are better handled on the mailing list (https://wiki.gnuradio.org/index.php/MailingLists)

thank you for that... brother . that issue has been ok but the new issue is being raised. \\\\\

gr::log :WARN: file_source0 - file size is not a multiple of item size
gr::log :ERROR: pagesize - no info; setting pagesize = 4096
gr::log :FATAL: tagged_stream_to_pdu0 - Missing a required length tag on port 0 at item #0
gr::log :ERROR: thread_body_wrapper - ERROR thread[thread-per-block[3]: <block tagged_stream_to_pdu(2)>]: Missing length tag.
