### ISSUE TITLE
KeyError: "No block with name 'top_block'"

### ISSUE THREAD

**Issue by k-bx** [gnuradio/gnuradio#5920]
### What happened?

Program misbehaves sometimes when I try to create a Hier Block [following tutorial](https://wiki.gnuradio.org/index.php?title=Hier_Blocks_and_Parameters). Error in terminal is:

```
(gnuradio-companion:2893): Gtk-WARNING **: 12:12:14.205: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner gnuradio+grc+gui+Notebook+Notebook)

(gnuradio-companion:2893): Gtk-WARNING **: 12:12:14.205: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner gnuradio+grc+gui+Notebook+Notebook)
Traceback (most recent call last):
  File "/usr/local/Cellar/gnuradio/3.10.2.0/lib/python3.9/site-packages/gnuradio/grc/gui/Application.py", line 314, in _handle_action
    top_block = flow_graph.get_block("top_block")
  File "/usr/local/Cellar/gnuradio/3.10.2.0/lib/python3.9/site-packages/gnuradio/grc/core/FlowGraph.py", line 215, in get_block
    raise KeyError('No block with name {!r}'.format(name))
KeyError: "No block with name 'top_block'"
```

### System Information

OS: Mac
GR Installation Method: brew install gnuradio

3.10.2.0 (Python 3.9.13)

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.2.0

### Steps to Reproduce the Problem

"Create Hier" step here https://wiki.gnuradio.org/index.php?title=Hier_Blocks_and_Parameters

### Relevant log output

```shell
(gnuradio-companion:2893): Gtk-WARNING **: 12:12:14.205: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner gnuradio+grc+gui+Notebook+Notebook)

(gnuradio-companion:2893): Gtk-WARNING **: 12:12:14.205: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner gnuradio+grc+gui+Notebook+Notebook)
Traceback (most recent call last):
  File "/usr/local/Cellar/gnuradio/3.10.2.0/lib/python3.9/site-packages/gnuradio/grc/gui/Application.py", line 314, in _handle_action
    top_block = flow_graph.get_block("top_block")
  File "/usr/local/Cellar/gnuradio/3.10.2.0/lib/python3.9/site-packages/gnuradio/grc/core/FlowGraph.py", line 215, in get_block
    raise KeyError('No block with name {!r}'.format(name))
KeyError: "No block with name 'top_block'"
```
```

**Comment by mormj** [comment]
Was unable to reproduce this error following the tutorial.  Please try again and reopen if this error still persists.
