### ISSUE TITLE
Port install gnuradio error on open MacOS

### ISSUE THREAD

**Issue by denysobukh** [gnuradio/gnuradio#5958]
### What happened?

I've installed gnuradio with `sudo port install gnuradio`

when run `gnuradio-companion` it fails with 
```
Traceback (most recent call last):
  File "/opt/local/bin/gnuradio-companion", line 112, in <module>
    run_main()
  File "/opt/local/bin/gnuradio-companion", line 105, in run_main
    sys.exit(main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gnuradio/grc/main.py", line 83, in main
    platform.build_library()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gnuradio/grc/core/platform.py", line 197, in build_library
    utils.hide_bokeh_gui_options_if_not_installed(self.blocks['options'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'options'
```

environment
```
 gnuradio-config-info --version
3.8.5.0
```

```
uname -a
Darwin i9.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
```

### System Information

OS: macOS 12.4
GR Installation Method: mac ports

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

```
sudo port install gr-osmosdr
gnuradio-companion
```

**Comment by denysobukh** [comment]
duplicate of https://github.com/gnuradio/gnuradio/issues/2873  
fixed with:  
```
rm -rf ~/.gnuradio/
```
