### ISSUE TITLE
dev-4.0: ninja test fails

### ISSUE THREAD

**Issue by dl1ksv** [gnuradio/gnuradio#6031]
**What happend**

After a successful build run
ninja test fails

**OS:** Fedora 35

**GR Installation** Method: Source

**GNU Radio Version**
4.0 (dev-4.0)

**Log output **

$ninja test
[0/1] Running all tests.
 1/49 pmt / PMT Basic Tests                        OK              0.03s
 2/49 pmt / PMT Scalar Tests                       OK              0.03s
 3/49 pmt / PMT Vector Tests                       OK              0.03s
 4/49 pmt / PMT Vector Of Pmts Tests               OK              0.02s
 5/49 pmt / PMT String Tests                       OK              0.02s
 6/49 pmt / PMT Map Tests                          OK              0.02s
 7/49 pmt / PMT Tag Tests                          OK              0.01s
 8/49 gnuradio / qa_fast_atan2f                    OK              0.05s
 9/49 gnuradio / qa_fxpt_nco                       OK              0.04s
10/49 gnuradio / qa_fxpt                           OK              0.04s
11/49 gnuradio / qa_math                           OK              0.03s
12/49 gnuradio / qa_sincos                         OK              0.03s
13/49 gnuradio / qa_fxpt_vco                       OK              0.07s
14/49 gnuradio / qa_conjugate                      FAIL            0.14s   exit status 1
>>> MALLOC_PERTURB_=140 PYTHONPATH=/home/schroer/gnuradiocomponents/gnuradio-4.0/build/python:/home/schroer/gnuradiocomponents/gnuradio-4.0/build/subprojects/pmt/python:/usr/local/gnuradio/lib64/python3.10/site-packages/:/usr/local/oot/lib64/python3.10/site-packages/ LD_LIBRARY_PATH=/home/schroer/gnuradiocomponents/gnuradio-4.0/build/schedulers/nbt/lib:/home/schroer/gnuradiocomponents/gnuradio-4.0/build/runtime/lib:/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/analog/lib:/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/blocks/lib:/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/fec/lib:/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/fft/lib:/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/fileio/lib:/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/filter/lib:/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/math/lib:/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/streamops/lib:/usr/local/gnuradio/lib64:/usr/local/volk/lib64:/usr/local/libiio/lib64:/usr/local/libad9361/lib:/usr/local/oot/lib64 /usr/bin/python3 /home/schroer/gnuradiocomponents/gnuradio-4.0/build/../blocklib/math/test/qa_conjugate.py
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stdout:
python/gnuradio/__init__.py
/home/schroer/gnuradiocomponents/gnuradio-4.0/build/python/gnuradio/__init__.py
/home/schroer/gnuradiocomponents/gnuradio-4.0/build/
stderr:
Traceback (most recent call last):
  File "/home/schroer/gnuradiocomponents/gnuradio-4.0/build/gr/python/gr/__init__.py", line 5, in <module>
    from .gr_python import *
ModuleNotFoundError: No module named 'gnuradio.gr.gr_python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/schroer/gnuradiocomponents/gnuradio-4.0/build/../blocklib/math/test/qa_conjugate.py", line 12, in <module>
    from gnuradio import gr, gr_unittest, blocks, math
  File "/home/schroer/gnuradiocomponents/gnuradio-4.0/build/gr/python/gr/__init__.py", line 9, in <module>
    from .gr_python import *
ImportError: /home/schroer/gnuradiocomponents/gnuradio-4.0/build/gr/python/gr/bindings/gr_python.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZTIN2gr9port_baseE

**Drilling it down to single imports leads to**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/schroer/gnuradiocomponents/gnuradio-4.0/build/gr/python/gr/__init__.py", line 9, in <module>
    from .gr_python import *
ImportError: /home/schroer/gnuradiocomponents/gnuradio-4.0/build/gr/python/gr/bindings/gr_python.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZTIN2gr9port_baseE
>>> from gnuradio import gr
Traceback (most recent call last):
  File "/home/schroer/gnuradiocomponents/gnuradio-4.0/build/gr/python/gr/__init__.py", line 5, in <module>
    from .gr_python import *
ModuleNotFoundError: No module named 'gnuradio.gr.gr_python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/schroer/gnuradiocomponents/gnuradio-4.0/build/gr/python/gr/__init__.py", line 9, in <module>
    from .gr_python import *
ImportError: /home/schroer/gnuradiocomponents/gnuradio-4.0/build/gr/python/gr/bindings/gr_python.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZTIN2gr9port_baseE
>>> from gnuradio import  gr_unittest
>>> from gnuradio import  blocks
Traceback (most recent call last):
  File "/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/blocks/python/blocks/__init__.py", line 5, in <module>
    from .blocks_python import *
ImportError: /home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/blocks/lib/libgnuradio-blocklib-blocks.so: undefined symbol: _ZN2gr5block4doneEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/blocks/python/blocks/__init__.py", line 9, in <module>
    from .blocks_python import *
ImportError: /home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/blocks/lib/libgnuradio-blocklib-blocks.so: undefined symbol: _ZN2gr5block4doneEv
>>> from gnuradio import math
Traceback (most recent call last):
  File "/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/math/python/math/__init__.py", line 6, in <module>
    from .math_python import *
ImportError: /home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/math/lib/libgnuradio-blocklib-math.so: undefined symbol: _ZN2gr5block4doneEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/math/python/math/__init__.py", line 10, in <module>
    from .math_python import *
ImportError: /home/schroer/gnuradiocomponents/gnuradio-4.0/build/blocklib/math/lib/libgnuradio-blocklib-math.so: undefined symbol: _ZN2gr5block4doneEv

It seems, that the libs are not linked correctly

**Comment by dl1ksv** [comment]
Perhaps, there is a conflict with an existing 3.10 installation.

**Comment by dl1ksv** [comment]
Some libs where linked against a gnuradio-runtime 3.10 lib. After fixing this, tests work now.
