### ISSUE TITLE
gr_modtool is broken on Windows

### ISSUE THREAD

**Issue by argilo** [gnuradio/gnuradio#6280]
Conda CI shows that gr_modtool is broken on Windows:
```
Traceback (most recent call last):
  File "%SRC_DIR%\gr-utils\modtool\tests\test_modtool.py", line 24, in <module>
    from gnuradio.modtool.core import ModToolNewModule
  File "%PREFIX%\lib\site-packages\gnuradio\modtool\core\__init__.py", line 11, in <module>
    from .base import ModTool, ModToolException, get_block_candidates, validate_name
  File "%PREFIX%\lib\site-packages\gnuradio\modtool\core\base.py", line 20, in <module>
    from ..tools import get_modname, SCMRepoFactory
  File "%PREFIX%\lib\site-packages\gnuradio\modtool\tools\__init__.py", line 13, in <module>
    from .code_generator import render_template
  File "%PREFIX%\lib\site-packages\gnuradio\modtool\tools\code_generator.py", line 14, in <module>
    from .util_functions import str_to_fancyc_comment
  File "%PREFIX%\lib\site-packages\gnuradio\modtool\tools\util_functions.py", line 14, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```
Python's readline module is not available on Windows. Readline support was added in #1529, but some accommodation for Windows will be needed to get gr_modtool working again on that platform.

Once this is fixed, `test_modtool` can be removed from the list of skipped tests in `.packaging/conda_recipe/bld.bat`.

**Comment by ryanvolz** [comment]
For whoever wants to take a crack at this, `pyreadline3` looks like a supportable (i.e. packaged in conda-forge already) alternative to use on Windows. It also looks straightforward to just catch the `ImportError` and fall back to no completion.
