### ISSUE TITLE
gr_modtool bind not working on 3.10 (from c++ to python)

### ISSUE THREAD

**Issue by cxaexeong** [gnuradio/gnuradio#6728]
### What happened?

A bug happened!

### System Information

OS:Ubuntu 22.04
GR Installation Method: Pybombs/

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

I made a custom module and finished up to cmake.
However, "macro name must be an identifier" error occurred during the make process.

### Relevant log output

```shell
[ 53%] /home/cylee/gr-cyleeModule/python/cyleeModule/bindings/../../../include/gnuradio/cyleeModule/cyle_ofdm.h

INFO Parsing source file "/home/cylee/gr-cyleeModule/include/gnuradio/cyleeModule/cyle_ofdm.h" ... 
In file included from <built-in>:440:
<command line>:3:9: error: macro name must be an identifier
#define -U__PIE__ 1
        ^
1 error generated.
Traceback (most recent call last):
  File "/home/cylee/gr-cyleeModule/python/cyleeModule/bindings/bind_oot_file.py", line 58, in <module>
    bg.gen_file_binding(args.filename)
  File "/usr/lib/python3/dist-packages/gnuradio/bindtool/core/generator.py", line 197, in gen_file_binding
    raise(e)
  File "/usr/lib/python3/dist-packages/gnuradio/bindtool/core/generator.py", line 184, in gen_file_binding
    header_info = parser.get_header_info(self.namespace)
  File "/usr/lib/python3/dist-packages/gnuradio/blocktool/core/parseheader_generic.py", line 330, in get_header_info
    decls = parser.parse(
  File "/usr/lib/python3/dist-packages/pygccxml/parser/__init__.py", line 51, in parse
    declarations = parser.read_files(files, compilation_mode)
  File "/usr/lib/python3/dist-packages/pygccxml/parser/project_reader.py", line 264, in read_files
    return self.__parse_file_by_file(files)
  File "/usr/lib/python3/dist-packages/pygccxml/parser/project_reader.py", line 292, in __parse_file_by_file
    decls = reader.read_file(header)
  File "/usr/lib/python3/dist-packages/pygccxml/parser/source_reader.py", line 303, in read_file
    return self.read_cpp_source_file(source_file)
  File "/usr/lib/python3/dist-packages/pygccxml/parser/source_reader.py", line 322, in read_cpp_source_file
    xml_file = self.create_xml_file(ffname)
  File "/usr/lib/python3/dist-packages/pygccxml/parser/source_reader.py", line 263, in create_xml_file
    raise RuntimeError(
RuntimeError: Error occurred while running CASTXML xml file does not exist
make[2]: *** [python/cyleeModule/bindings/CMakeFiles/cyle_ofdm_python.cc_regen_bindings.dir/build.make:73: ../python/cyleeModule/bindings}/cyle_ofdm_python.cc] Error 1
make[1]: *** [CMakeFiles/Makefile2:387: python/cyleeModule/bindings/CMakeFiles/cyle_ofdm_python.cc_regen_bindings.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by marcusmueller** [comment]
```

INFO Parsing source file "/home/cylee/gr-cyleeModule/include/gnuradio/cyleeModule/cyle_ofdm.h" ... 
In file included from <built-in>:440:
<command line>:3:9: error: macro name must be an identifier
#define -U__PIE__ 1
        ^
```

That's a problem in gr-cyleeModule, not GNU Radio!
