### ISSUE TITLE
Hier Block (QT GUI) not working due to missing Qt imports

### ISSUE THREAD

**Issue by eltos** [gnuradio/gnuradio#6807]
### What happened?

After updating from v3.10.5.1 to v3.10.7.0 Hier Blocks (QT GUI) are no longer working since the generated Python files are missing the `from PyQt5 import Qt` statement.

### System Information

OS: Ubuntu
GR Installation Method: Build from source, tag v3.10.7.0

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.7.0

### Steps to Reproduce the Problem

Steps to reproduce:
- Start GNU Radio 3.10.7.0
- Create a new flow graph
- In the options block, select "Hier Block (QT GUI)" for generate options
- Generate the flow graph
- Inspect the generated Python file in `~/.grc_gnuradio` and notice the missing Qt import
- Create another flow graph, import the Hier block and try to run it
- Get the error:
```text
Traceback (most recent call last):
  File "/home/xxxx/untitled2.py", line 26, in <module>
    from untitled import untitled  # grc-generated hier_block
  File "/home/xxxx/.grc_gnuradio/untitled.py", line 22, in <module>
    class untitled(gr.hier_block2, Qt.QWidget):
NameError: name 'Qt' is not defined
```

### Relevant observations

It looks like this import statement has recently been removed from a lot of block YML files, since it is added by the code generator anyways for QT GUI flow graphs. However, this is not true for QT GUI Hier Blocks.
For example [here](https://github.com/gnuradio/gnuradio/blob/2180acce77829b2c082601b182ca45629233fc8d/grc/blocks/options.block.yml#L146-L148) the check

% if generate_options == 'qt_gui':
from PyQt5 import Qt
from gnuradio import qtgui
%endif

does not include hier blocks (which are `'hb_qt_gui'`). There might be other places where this kind of check is missing.

**Comment by eltos** [comment]
The current workaround is to manually add the import statement via an "Import" block in the flow graph of the QT GUI Hier Block.
