### ISSUE TITLE
pfb.py typo

### ISSUE THREAD

**Issue by aaryswastaken** [gnuradio/gnuradio#6833]
In [line 72](https://github.com/gnuradio/gnuradio/blob/e1bf7314f060816aa158e9a55b235c4defbae6c0/gr-filter/python/filter/pfb.py#L72C26-L72C26) of `gr-filter/python/filter/pfb.py`, the `return tap` should be replaced by `return taps`  

Having the following Traceback while running `sudo grgsm_scanner -v -d`: 
```
Traceback (most recent call last):
  File "/usr/bin/grgsm_scanner", line 439, in <module>
    main()
  File "/usr/bin/grgsm_scanner", line 435, in main
    do_scan(options.samp_rate, options.band, options.speed,
  File "/usr/bin/grgsm_scanner", line 331, in do_scan
    scanner = wideband_scanner(rec_len=6 - speed,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/grgsm_scanner", line 239, in __init__
    self.wideband_receiver = wideband_receiver(OSR=4, fc=carrier_frequency, samp_rate=sample_rate)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/grgsm_scanner", line 145, in __init__
    self.__init(OSR, fc, samp_rate)
  File "/usr/bin/grgsm_scanner", line 160, in __init
    self.pfb_channelizer_ccf_0 = pfb.channelizer_ccf(
                                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gnuradio/filter/pfb.py", line 39, in __init__
    self._taps = self.create_taps(self._nchans, atten)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gnuradio/filter/pfb.py", line 72, in create_taps
    return tap
           ^^^
NameError: name 'tap' is not defined. Did you mean: 'taps'?
```

And the issue being fixed with what I wrote on first line

**Comment by aaryswastaken** [comment]
Closed because of merge
