### ISSUE TITLE
qa_fecapi_repetition is flaky

### ISSUE THREAD

**Issue by argilo** [gnuradio/gnuradio#7022]
Debian build logs show that qa_fecapi_repetition fails on i386:

https://buildd.debian.org/status/fetch.php?pkg=gnuradio&arch=i386&ver=3.10.9.0%7Erc1-2&stamp=1703091669&raw=0
https://buildd.debian.org/status/fetch.php?pkg=gnuradio&arch=i386&ver=3.10.9.0%7Erc1-3&stamp=1703129935&raw=0

```
        Start 118: qa_fecapi_repetition
118/264 Test #118: qa_fecapi_repetition .........................***Failed    1.54 sec
FFFF........
======================================================================
FAIL: test_async_00 (__main__.test_fecapi_repetition.test_async_00) (packed=True, rev_pack=True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/gr-fec/python/fec/qa_fecapi_repetition.py", line 174, in test_async_00
    self.assertSequenceEqualGR(data_in, data_out)
  File "/<<PKGBUILDDIR>>/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 115, in assertSequenceEqualGR
    self.assertEqual(len(data_in), len(data_out), msg="Lengths do not match")
AssertionError: 15360 != 14848 : Lengths do not match

======================================================================
FAIL: test_async_00 (__main__.test_fecapi_repetition.test_async_00) (packed=True, rev_pack=False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/gr-fec/python/fec/qa_fecapi_repetition.py", line 174, in test_async_00
    self.assertSequenceEqualGR(data_in, data_out)
  File "/<<PKGBUILDDIR>>/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 115, in assertSequenceEqualGR
    self.assertEqual(len(data_in), len(data_out), msg="Lengths do not match")
AssertionError: 15360 != 14848 : Lengths do not match

======================================================================
FAIL: test_async_00 (__main__.test_fecapi_repetition.test_async_00) (packed=False, rev_pack=True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/gr-fec/python/fec/qa_fecapi_repetition.py", line 174, in test_async_00
    self.assertSequenceEqualGR(data_in, data_out)
  File "/<<PKGBUILDDIR>>/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 115, in assertSequenceEqualGR
    self.assertEqual(len(data_in), len(data_out), msg="Lengths do not match")
AssertionError: 15360 != 15296 : Lengths do not match

======================================================================
FAIL: test_async_00 (__main__.test_fecapi_repetition.test_async_00) (packed=False, rev_pack=False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/gr-fec/python/fec/qa_fecapi_repetition.py", line 174, in test_async_00
    self.assertSequenceEqualGR(data_in, data_out)
  File "/<<PKGBUILDDIR>>/gnuradio-runtime/python/gnuradio/gr_unittest.py", line 115, in assertSequenceEqualGR
    self.assertEqual(len(data_in), len(data_out), msg="Lengths do not match")
AssertionError: 15360 != 15296 : Lengths do not match

----------------------------------------------------------------------
Ran 9 tests in 1.202s

FAILED (failures=4)
```

**Comment by argilo** [comment]
So far I haven't been able to reproduce the failure locally.

This failure could have the same root cause as #6628, as the symptoms are similar.

**Comment by argilo** [comment]
As with #6628, I was able to reproduce by adding load with `stress -c 16`.

**Comment by argilo** [comment]
I had a closer look, and I'm convinced now that this shares the same root cause as #6628, so I'll close it as a duplicate and expand the scope of #6628.

**Comment by argilo** [comment]
I was too quick to close this as a duplicate of #6628. It turns out the root cause is separate: https://github.com/gnuradio/gnuradio/issues/6628#issuecomment-1867736605

**Comment by argilo** [comment]
The cause of this bug is that FEC Async Decoder calculates the frame length in floating point, then converts it to an integer without rounding. Floating point error can cause it to be one bit/byte too low.
