### ISSUE TITLE
audio: add 96 kHz and 192 kHz options to audio sink grc

### ISSUE THREAD

**Issue by Randrianasulu** [gnuradio/gnuradio#7155]
### What happened?

Using self-compiled  gnuradio-companion gui  3.9.8.0  I tried  to modify friend's schematic  to do single sideband modulation using audio sources for both input (microphone) and output (audio interface with hydrophone attatched). Julian works on Mac and I on Linux PC. So  device names  differ. But I think there is something  wrong with my ALSA setup because when I try to run script I get:

```

```

### System Information

OS: Slackware 15.0 i586
GR Installation Method: Slackbuild

### GNU Radio Version

3.9  (maint-3.9)

### Specific Version

3.9.8.0

### Steps to Reproduce the Problem

[RandytestTX2modified_copy-1.grc.zip](https://github.com/gnuradio/gnuradio/files/14465188/RandytestTX2modified_copy-1.grc.zip)

Run attached  grc file. It will fail to set 192 Khz ALSA sink, probably.

Minor think dropdown  gui menu only contain frequencies up to 48Khz.

### Relevant log output

```shell
bash-5.1$ gnuradio-companion ~/Desktop/RandytestTX2modified_copy.grc
<<< Welcome to GNU Radio Companion 3.9.8.0 >>>

Block paths:
        /usr/share/gnuradio/grc/blocks

Loading: "/home/guest/Desktop/RandytestTX2modified_copy.grc"
>>> Done

Generating: '/home/guest/Desktop/RandytestTX2.py'

Generating: '/home/guest/Desktop/RandytestTX2.py'

Executing: /usr/bin/python3 -u /home/guest/Desktop/RandytestTX2.py

gr::log :ERROR: fft::import_wisdom - can't import wisdom from /home/guest/.gr_fftw_wisdom
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM Micro MacBook Air
gr::log :ERROR: audio_alsa_source0 - [Micro MacBook Air]: Нет такого файла или каталога
Traceback (most recent call last):
  File "/home/guest/Desktop/RandytestTX2.py", line 243, in <module>
    main()
  File "/home/guest/Desktop/RandytestTX2.py", line 221, in main
    tb = top_block_cls()
  File "/home/guest/Desktop/RandytestTX2.py", line 151, in __init__
    self.audio_source_0 = audio.source(48000, 'Micro MacBook Air', True)
RuntimeError: audio_alsa_source

>>> Done (return code 1)

Generating: '/home/guest/Desktop/RandytestTX2.py'

Executing: /usr/bin/python3 -u /home/guest/Desktop/RandytestTX2.py


>>> Done

Generating: '/home/guest/Desktop/RandytestTX2.py'

Executing: /usr/bin/python3 -u /home/guest/Desktop/RandytestTX2.py

gr::log :ERROR: audio_alsa_sink0 - [default]: set_periods failed: Недопустимый аргумент
Traceback (most recent call last):
  File "/home/guest/Desktop/RandytestTX2.py", line 247, in <module>
    main()
  File "/home/guest/Desktop/RandytestTX2.py", line 225, in main
    tb = top_block_cls()
  File "/home/guest/Desktop/RandytestTX2.py", line 153, in __init__
    self.audio_sink_0 = audio.sink(samp_rate, '', True)
RuntimeError: audio_alsa_sink

>>> Done (return code 1)

Generating: '/home/guest/Desktop/RandytestTX2.py'

Executing: /usr/bin/python3 -u /home/guest/Desktop/RandytestTX2.py

gr::log :ERROR: audio_alsa_sink0 - [default]: set_periods failed: Недопустимый аргумент
Traceback (most recent call last):
  File "/home/guest/Desktop/RandytestTX2.py", line 247, in <module>
    main()
  File "/home/guest/Desktop/RandytestTX2.py", line 225, in main
    tb = top_block_cls()
  File "/home/guest/Desktop/RandytestTX2.py", line 153, in __init__
    self.audio_sink_0 = audio.sink(samp_rate, 'default', False)
RuntimeError: audio_alsa_sink

>>> Done (return code 1)

Generating: '/home/guest/Desktop/RandytestTX2.py'

Executing: /usr/bin/python3 -u /home/guest/Desktop/RandytestTX2.py


>>> Done

Generating: '/home/guest/Desktop/RandytestTX2.py'

Executing: /usr/bin/python3 -u /home/guest/Desktop/RandytestTX2.py

gr::log :ERROR: audio_alsa_sink0 - [default]: set_periods failed: Недопустимый аргумент
Traceback (most recent call last):
  File "/home/guest/Desktop/RandytestTX2.py", line 247, in <module>
    main()
  File "/home/guest/Desktop/RandytestTX2.py", line 225, in main
    tb = top_block_cls()
  File "/home/guest/Desktop/RandytestTX2.py", line 153, in __init__
    self.audio_sink_0 = audio.sink(192000, 'default', False)
RuntimeError: audio_alsa_sink

>>> Done (return code 1)
```

**Comment by willcode** [comment]
Agree that there should be 96 kHz and 192 kHz options in the menu.

Your GRC runs for me, but it doesn't do anything. I don't know what happens when you use a 48k audio source and a 192k audio sink using the same card. in any case, no crash.
