### ISSUE TITLE
gr_modtool bind fails when using regex for modules created prior to 3.10.

### ISSUE THREAD

**Issue by jason-merlo** [gnuradio/gnuradio#7169]
### What happened?

When attempting to run `gr_modtool bind` on all blocks for an OOT created with API Post-3.8 while running GNU Radio v3.10, the command fails due to an incorrect search path.

### System Information

OS: Linux, macOS, and Windows (reproduced across all)
GR Installation Method: source, and conda (both have the issue)

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.9.2

### Steps to Reproduce the Problem

**Steps to reproduce:**

1. Using gnuradio v3.9 create an OOT block
2. Using gnuradio v3.10 run `gr_modtool bind` to rebind all blocks
```
gr-test git:(main) : gr_modtool bind
GNU Radio module name identified: delta_time_utils
Which blocks do you want to parse? (Regex):
... (truncated--see full output in log section) ... 
FileNotFoundError: [Errno 2] No such file or directory: 'include/gnuradio/test/CMakeLists.txt'
```
The same error is generated when a block name is specified, e.g., `Which blocks do you want to parse? (Regex): blockname`.

**The problem:**
The `CMakeLists.txt` file it is looking for actually resides in `/include/test/CMakeLists.txt` for OOT modules created with API's prior to 3.10.

The regex function, invoked when no block name is specified after `gr_modtool bind`, attempts to get the block names from the `get_block_names` function in [`/gr-utils/modtool/tools/util_functions.py`](https://github.com/gnuradio/gnuradio/blob/188c89f98832f6dcb45480c7a8566218c7d3bd89/gr-utils/modtool/tools/util_functions.py#L134).  This file does not check the API Version used to create the OOT module, however it is called only by `gr_modtool bind` _and_ `gr_modtool rm`, both of which have access to the API version the module was created with (via `self.info['version']`).  

**Possible fixes:**
Possible solutions could involve either:

1. Passing the API version used to the `get_block_names` function, and looking up the proper location of the CMakeLists.txt for the header files (similar to the [`ModToolGenBindings.run()` function](https://github.com/gnuradio/gnuradio/blob/188c89f98832f6dcb45480c7a8566218c7d3bd89/gr-utils/modtool/core/bind.py#L73))
2. Add the path to search for the CMakeLists.txt for header files in as an argument to `get_block_names`
3. Modify `get_block_names` to search through the `./lib/CMakeLists.txt` file for `.cc` files in the first list following the `include(GrPlatform)` directive

### Relevant log output

```shell
gr-test git:(main) ✗ gr_modtool bind
GNU Radio module name identified: test
Which blocks do you want to parse? (Regex):
Traceback (most recent call last):
  File "/Users/username/miniforge3/envs/grdev/bin/gr_modtool", line 18, in <module>
    cli()
  File "/Users/username/miniforge3/envs/grdev/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/miniforge3/envs/grdev/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/username/miniforge3/envs/grdev/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/miniforge3/envs/grdev/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/miniforge3/envs/grdev/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/miniforge3/envs/grdev/lib/python3.12/site-packages/gnuradio/modtool/cli/base.py", line 135, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/miniforge3/envs/grdev/lib/python3.12/site-packages/gnuradio/modtool/cli/bind.py", line 49, in cli
    run(self)
  File "/Users/username/miniforge3/envs/grdev/lib/python3.12/site-packages/gnuradio/modtool/cli/base.py", line 155, in run
    module.run()
  File "/Users/username/miniforge3/envs/grdev/lib/python3.12/site-packages/gnuradio/modtool/core/bind.py", line 68, in run
    blocknames_to_process = get_block_names(
                            ^^^^^^^^^^^^^^^^
  File "/Users/username/miniforge3/envs/grdev/lib/python3.12/site-packages/gnuradio/modtool/tools/util_functions.py", line 139, in get_block_names
    with open(f'include/gnuradio/{modname}/CMakeLists.txt', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/gnuradio/test/CMakeLists.txt'
```

**Comment by willcode** [comment]
Thanks for the detailed bug report. This should give someone a good idea for a fix.
