### ISSUE TITLE
Block rotation in GRC QT do not restrict rotation to [0,359] causing GRC GTK to break when opening

### ISSUE THREAD

**Issue by jason-merlo** [gnuradio/gnuradio#7200]
### What happened?

When using GRC QT, block rotations are integrated, meaning if the block is rotated greater than 270 (360 or above) it will cause GRC GRK to fail to render properly (and even cause the entire GRC GTK UI to start glitching outside of the canvas).

Expected rotation in GRC GTK:
<img width="1133" alt="Screenshot 2024-03-16 at 16 00 43" src="https://github.com/gnuradio/gnuradio/assets/2801596/283d8302-4407-4dea-a67f-2f1ac09715a9">

After rotating to -180 in GRC QT then opening again in GRC GTK:
<img width="1136" alt="Screenshot 2024-03-16 at 16 02 29" src="https://github.com/gnuradio/gnuradio/assets/2801596/82978b0f-7288-49b1-bac9-f82668a13781">

### System Information

OS: macOS
GR Installation Method: Source (inside Conda environment)

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.11.0.0git-681-gc1d98007

### Steps to Reproduce the Problem

1. Create/Open a flow graph in GRC QT
2. Rotate a block to a total _integrated_ rotation outside [0,90,180,270] (left causes a negative number)
3. Save the flow graph
4. Open in GRC GTK

### Relevant log output

```shell
--- The following is repeated MANY times when opening in GRC GTK ---

Traceback (most recent call last):
  File "/Users/jason/miniforge3/envs/grdev/lib/python3.12/site-packages/gnuradio/grc/gui/Application.py", line 788, in _handle_action
    flow_graph_update()
  File "/Users/jason/miniforge3/envs/grdev/lib/python3.12/site-packages/gnuradio/grc/gui/Application.py", line 112, in flow_graph_update
    fg.update()
  File "/Users/jason/miniforge3/envs/grdev/lib/python3.12/site-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 203, in update
    self.create_shapes()
  File "/Users/jason/miniforge3/envs/grdev/lib/python3.12/site-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 517, in create_shapes
    element.create_shapes()
  File "/Users/jason/miniforge3/envs/grdev/lib/python3.12/site-packages/gnuradio/grc/gui/canvas/block.py", line 135, in create_shapes
    self.bounds_from_area(self._area)
  File "/Users/jason/miniforge3/envs/grdev/lib/python3.12/site-packages/gnuradio/grc/gui/canvas/drawable.py", line 101, in bounds_from_area
    x1, y1, w, h = area
    ^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 0)
```

**Comment by willcode** [comment]
Thanks for the report. Let us know if the simple fix in 7201 works for you.

**Comment by jason-merlo** [comment]
That seems to have solve the problem.  Rotating many times in QT and re-opening in GTK works as expected. Thanks!
