### ISSUE TITLE
gnuradio encountered errors when trying to display non utf8 string

### ISSUE THREAD

**Issue by cxp10** [gnuradio/gnuradio#7282]
### What happened?

If the Message PMT parameter of Message Strobe block is set to  `pmt.intern(b'\xff')`, some `UnicodeEncodeError` will only appear in the background terminal window. This should be a bug.
After that, gnuradio probably still works, although the preview of b'\xff' disappears.
At worst, if the message strobe is the last block to be added to the flow graph, gnuradio will crash when the flow graph is loaded.

possible cause
https://github.com/gnuradio/gnuradio/issues/3778  flawed `__str()__` method
similar issue
https://github.com/gnuradio/gnuradio/issues/3398 same issue for u8vector
https://github.com/gnuradio/gnuradio/issues/7143 possibly because `print()` called  `__str()__`

### System Information

OS: Ubuntu 22
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

v3.10.9.2-60-gb0766390

### Steps to Reproduce the Problem

Create a new grc flow graph,
add a message strobe block,
change the message pmt to  `pmt.intern(b'\xff')`,
Then there will be `UnicodeEncodeError` in the terminal window.
Save the grc file,
reopen the grc file,
Then gnuradio would crash.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/PropsDialog.py", line 320, in _handle_response
    child.apply_pending_changes()
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/ParamWidgets.py", line 166, in apply_pending_changes
    self._apply_change()
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/ParamWidgets.py", line 156, in _apply_change
    self._update_gui()
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/ParamWidgets.py", line 126, in _update_gui
    self.set_tooltip_text(self.param.format_tooltip_text())
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/canvas/param.py", line 78, in format_tooltip_text
    value = str(value)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/Application.py", line 570, in _handle_action
    flow_graph_update()
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/Application.py", line 112, in flow_graph_update
    fg.update()
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 202, in update
    self.create_labels()
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 510, in create_labels
    element.create_labels(cr)
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/canvas/block.py", line 182, in create_labels
    markups = [param.format_block_surface_markup()
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/canvas/block.py", line 182, in <listcomp>
    markups = [param.format_block_surface_markup()
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/grc/gui/canvas/param.py", line 167, in format_block_surface_markup
    is_evaluated = self.value != str(self.get_evaluated())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by wlmqljj** [comment]
I use radioconda on windows11.
I have similar issue with you,
I run Windows11 with chinese locale environment, so the terminal codec is gbk,
then every time I run grc python script using GNU Radio Companion, It will throw 
```
Traceback (most recent call last):
  File "C:\radioconda\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\radioconda\Lib\site-packages\gnuradio\grc\gui\Executor.py", line 115, in run
    r = self.process.stdout.read(1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8e in position 44: illegal multibyte sequence
```
And the thread seems working, but I can't terminate the process with stop button that GNU Radio Companion providing. 
The stop button just not works.  

So I edit 
https://github.com/gnuradio/gnuradio/blob/3a18360c0a449b75907d267238179eea266691f6/grc/gui_qt/components/executor.py#L97-L106
the statement `r = self.process.stdout.read(1) ` to
```
    def run(self):
        """
        Wait on the executing process by reading from its stdout.
        Use GObject.idle_add when calling functions that modify gtk objects.
        """
        # handle completion
        r = "\n"
        while r:
            GLib.idle_add(Messages.send_verbose_exec, r)
            # just wrap with try except block to ignore the error
            try:
                r = self.process.stdout.read(1)
            except UnicodeDecodeError:
                print("Decode error occurred.")
                pass
```
using try except pass wrap statement fixes the issue for me.  
It is not the appropriate approach until a fix shows up clearly , but it works.  
This is my experience sharing for you. :)
