### ISSUE TITLE
gnuradio-companion --qt missing oot module causes SIGABRT in python

### ISSUE THREAD

**Issue by chrisjohgorman** [gnuradio/gnuradio#7295]
### What happened?

I got a sigabrt from python when trying to load a grc file.  
I believe this is caused by the fact that my install was missing an out of tree module referenced in the grc file.  Installing the missing oot module caused the error to disappear.

```
[chris@descartes ~]$ Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/gnuradio/grc/gui_qt/components/canvas/port.py", line 81, in itemChange
    self.update_connections()
  File "/usr/lib/python3.12/site-packages/gnuradio/grc/gui_qt/components/canvas/port.py", line 77, in update_connections
    conn.gui.set_rotation(self.parentItem().rotation())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'rotation'
```
The following is the core file backtrace.
```
Core was generated by `/usr/bin/python3 /usr/bin/gnuradio-companion --qt'.
Program terminated with signal SIGABRT, Aborted.
#0  0x0000715f3eaab32c in ?? () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x715f3f287740 (LWP 989090))]
(gdb) bt
#0  0x0000715f3eaab32c in ??? () at /usr/lib/libc.so.6
#1  0x0000715f3ea5a6c8 in raise () at /usr/lib/libc.so.6
#2  0x0000715f3ea424b8 in abort () at /usr/lib/libc.so.6
#3  0x0000715efda980c2 in QMessageLogger::fatal(char const*, ...) const ()
    at /usr/lib/libQt5Core.so.5
#4  0x0000715efe048048 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtCore.abi3.so
#5  0x0000715f01a3fe75 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/sip.cpython-312-x86_64-linux-gnu.so
#6  0x0000715efd08d837 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#7  0x0000715efd230975 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#8  0x0000715efcc8fb30 in ??? () at /usr/lib/libQt5Widgets.so.5
#9  0x0000715efcca9868 in QGraphicsView::paintEvent(QPaintEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#10 0x0000715efd1e9724 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#11 0x0000715efc98e040 in QWidget::event(QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#12 0x0000715efca3ca83 in QFrame::event(QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging-- 
#13 0x0000715efd1ea5ec in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#14 0x0000715efdc90a42 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#15 0x0000715efc9578ef in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /usr/lib/libQt5Widgets.so.5
#16 0x0000715efd2e3b57 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#17 0x0000715efdc93a68 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /usr/lib/libQt5Core.so.5
#18 0x0000715efc981f7b in QWidgetPrivate::sendPaintEvent(QRegion const&) ()
    at /usr/lib/libQt5Widgets.so.5
#19 0x0000715efc98337d in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt5Widgets.so.5
#20 0x0000715efc983d8e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/libQt5Widgets.so.5
#21 0x0000715efc98281e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt5Widgets.so.5
#22 0x0000715efc983d8e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, --Type <RET> for more, q to quit, c to continue without paging--
QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/libQt5Widgets.so.5
#23 0x0000715efc98281e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt5Widgets.so.5
#24 0x0000715efc983d8e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/libQt5Widgets.so.5
#25 0x0000715efc983bec in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/libQt5Widgets.so.5
#26 0x0000715efc98281e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt5Widgets.so.5
#27 0x0000715efc983d8e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/libQt5Widgets.so.5
#28 0x0000715efc983bec in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivat--Type <RET> for more, q to quit, c to continue without paging--
e::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/libQt5Widgets.so.5
#29 0x0000715efc983bec in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/libQt5Widgets.so.5
#30 0x0000715efc98281e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/libQt5Widgets.so.5
#31 0x0000715efc9636d9 in ??? () at /usr/lib/libQt5Widgets.so.5
#32 0x0000715efc98e0d1 in QWidget::event(QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#33 0x0000715efd19567c in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#34 0x0000715efc9578ff in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /usr/lib/libQt5Widgets.so.5
#35 0x0000715efd2e3b57 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#36 0x0000715efdc93a68 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /usr/lib/libQt5Core.so.5
#37 0x0000715efdc989cb in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#38 0x0000715efcc73ee7 in ??? () at /usr/lib/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--c
#39 0x0000715efdcbb4da in QObject::event(QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#40 0x0000715efd1fddfc in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#41 0x0000715efc9578ff in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /usr/lib/libQt5Widgets.so.5
#42 0x0000715efd2e3b57 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#43 0x0000715efdc93a68 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /usr/lib/libQt5Core.so.5
#44 0x0000715efdc989cb in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#45 0x0000715efdcdea48 in ??? () at /usr/lib/libQt5Core.so.5
#46 0x0000715f04082199 in ??? () at /usr/lib/libglib-2.0.so.0
#47 0x0000715f040e13bf in ??? () at /usr/lib/libglib-2.0.so.0
#48 0x0000715f04081712 in g_main_context_iteration ()
    at /usr/lib/libglib-2.0.so.0
#49 0x0000715efdce288c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#50 0x0000715efdc92774 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#51 0x0000715efdc93c13 in QCoreApplication::exec() ()
    at /usr/lib/libQt5Core.so.5
#52 0x0000715efd2de8f0 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#53 0x0000715f3eda52ed in ??? () at /usr/lib/libpython3.12.so.1.0
#54 0x0000715f3ed8550b in _PyObject_MakeTpCall ()
    at /usr/lib/libpython3.12.so.1.0
#55 0x0000715f3ec8bdfa in ??? () at /usr/lib/libpython3.12.so.1.0
#56 0x0000715f3ee3d767 in PyEval_EvalCode () at /usr/lib/libpython3.12.so.1.0
#57 0x0000715f3ee608b7 in ??? () at /usr/lib/libpython3.12.so.1.0
#58 0x0000715f3ee5b9dc in ??? () at /usr/lib/libpython3.12.so.1.0
#59 0x0000715f3ee74f33 in ??? () at /usr/lib/libpython3.12.so.1.0
#60 0x0000715f3ee74346 in _PyRun_SimpleFileObject ()
    at /usr/lib/libpython3.12.so.1.0
#61 0x0000715f3ee73f88 in _PyRun_AnyFileObject ()
    at /usr/lib/libpython3.12.so.1.0
#62 0x0000715f3ee6cc67 in Py_RunMain () at /usr/lib/libpython3.12.so.1.0
#63 0x0000715f3ee28fab in Py_BytesMain () at /usr/lib/libpython3.12.so.1.0
#64 0x0000715f3ea43cd0 in ??? () at /usr/lib/libc.so.6
#65 0x0000715f3ea43d8a in __libc_start_main () at /usr/lib/libc.so.6
#66 0x0000619c6fe33045 in _start ()
```

### System Information

OS: Arch Linux
Gnu Radio installation, built from source for 3.10.10.0

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.10.0

### Steps to Reproduce the Problem

1) Run gnuradio-companion --qt
2) Attempt to load a grc file with out of tree module blocks in it that are not currently installed.  (For example install gr-satellites, build a flowgraph with one of the satellite blocks, then remove gr-satellites and try to load the grc file you created.)

**Comment by haakov** [comment]
Can reproduce. This error occurs when a flowgraph has missing blocks that are connected to other blocks. Fix coming shortly

**Comment by haakov** [comment]
@chrisjohgorman Does https://github.com/gnuradio/gnuradio/pull/7329 fix the issue?

**Comment by chrisjohgorman** [comment]
@haakov #7329 fixes it for me.   Thanks.

**Comment by chrisjohgorman** [comment]
@haakov, apparently my brain is broken today.  Should I close this as you've fixed it?

**Comment by haakov** [comment]
No, we can keep it open until the fix has been merged :)
