### ISSUE TITLE
grc-qt variable_editor_disable selection of a variable causes python to SIGABRT

### ISSUE THREAD

**Issue by chrisjohgorman** [gnuradio/gnuradio#7304]
### What happened?

Right clicking on variable editor window gives a list of options for editing variables.  Choose a variable that is on the canvas and right click on it in the variable editor window.  This will bring up a menu of items to choose from.  Selecting `variable_editor_enable` or `variable_editor_disable` will cause a crash.

The following output is from selecting the samp_rate variable and disabling it.  In the gtk interface this disables the variable selected on the canvas.

```
[chris@descartes ~]$ gnuradio-companion --qt
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/gnuradio/grc/gui_qt/components/variable_editor.py", line 208, in <lambda>
    self.disable.triggered.connect(lambda: var_edit.handle_action(VariableEditorAction.DISABLE_BLOCK))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gnuradio/grc/gui_qt/components/variable_editor.py", line 185, in handle_action
    self._block.state = 'disabled'
    ^^^^^^^^^^^
AttributeError: 'VariableEditor' object has no attribute '_block'. Did you mean: 'new_block'?
[1]+  Done                    gnuradio-companion --qt
Aborted (core dumped)
```

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/bin/python3 /usr/bin/gnuradio-companion --qt'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007aedbb8ac194 in ?? () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7aedbc0d6740 (LWP 396335))]
(gdb) bt
#0  0x00007aedbb8ac194 in ??? () at /usr/lib/libc.so.6
#1  0x00007aedbb858d70 in raise () at /usr/lib/libc.so.6
#2  0x00007aedbb8404c0 in abort () at /usr/lib/libc.so.6
#3  0x00007aed7a8980c2 in QMessageLogger::fatal(char const*, ...) const ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007aed7ae48048 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtCore.abi3.so
#5  0x00007aed7afae595 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtCore.abi3.so
#6  0x00007aed7aac85d7 in ??? () at /usr/lib/libQt5Core.so.5
#7  0x00007aed7974abb7 in QAction::triggered(bool) ()
    at /usr/lib/libQt5Widgets.so.5
#8  0x00007aed7975060b in QAction::activate(QAction::ActionEvent) ()
    at /usr/lib/libQt5Widgets.so.5
#9  0x00007aed798d337b in ??? () at /usr/lib/libQt5Widgets.so.5
#10 0x00007aed798d349d in ??? () at /usr/lib/libQt5Widgets.so.5
#11 0x00007aed79f86e14 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#12 0x00007aed7978e1a1 in QWidget::event(QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#13 0x00007aed79f860fc in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#14 0x00007aed797578ff in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /usr/lib/libQt5Widgets.so.5
#15 0x00007aed7975cdaf in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#16 0x00007aed7a0e3b57 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#17 0x00007aed7aa93a68 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /usr/lib/libQt5Core.so.5
#18 0x00007aed7975b0ea in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
    at /usr/lib/libQt5Widgets.so.5
#19 0x00007aed797ac9c4 in ??? () at /usr/lib/libQt5Widgets.so.5
#20 0x00007aed797adc17 in ??? () at /usr/lib/libQt5Widgets.so.5
#21 0x00007aed797578ff in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /usr/lib/libQt5Widgets.so.5
#22 0x00007aed7a0e3b57 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#23 0x00007aed7aa93a68 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /usr/lib/libQt5Core.so.5
#24 0x00007aed78f3194c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#25 0x00007aed78f1a6d5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#26 0x00007aed7312e500 in ??? () at /usr/lib/libQt5XcbQpa.so.5
#27 0x00007aed80f31199 in ??? () at /usr/lib/libglib-2.0.so.0
#28 0x00007aed80f903bf in ??? () at /usr/lib/libglib-2.0.so.0
#29 0x00007aed80f30712 in g_main_context_iteration ()
    at /usr/lib/libglib-2.0.so.0
#30 0x00007aed7aae288c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#31 0x00007aed7aa92774 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#32 0x00007aed798dac28 in ??? () at /usr/lib/libQt5Widgets.so.5
#33 0x00007aed798dad43 in QMenu::exec(QPoint const&, QAction*) ()
    at /usr/lib/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--c
#34 0x00007aed79f8b0ef in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#35 0x00007aedbbba52c6 in ??? () at /usr/lib/libpython3.12.so.1.0
#36 0x00007aedbbb8550b in _PyObject_MakeTpCall ()
    at /usr/lib/libpython3.12.so.1.0
#37 0x00007aedbba8bdfa in ??? () at /usr/lib/libpython3.12.so.1.0
#38 0x00007aedbbbd4e06 in ??? () at /usr/lib/libpython3.12.so.1.0
#39 0x00007aed7b276b5c in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/sip.cpython-312-x86_64-linux-gnu.so
#40 0x00007aed7b278753 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/sip.cpython-312-x86_64-linux-gnu.so
#41 0x00007aed7a082519 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#42 0x00007aed7978e749 in QWidget::event(QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#43 0x00007aed7a08052c in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#44 0x00007aed797578ff in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /usr/lib/libQt5Widgets.so.5
#45 0x00007aed7975d284 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#46 0x00007aed7a0e3b57 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#47 0x00007aed7aa93a68 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /usr/lib/libQt5Core.so.5
#48 0x00007aed797ac654 in ??? () at /usr/lib/libQt5Widgets.so.5
#49 0x00007aed797adc17 in ??? () at /usr/lib/libQt5Widgets.so.5
#50 0x00007aed797578ff in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /usr/lib/libQt5Widgets.so.5
#51 0x00007aed7a0e3b57 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#52 0x00007aed7aa93a68 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /usr/lib/libQt5Core.so.5
#53 0x00007aed78f3194c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#54 0x00007aed78f1a6d5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#55 0x00007aed7312e500 in ??? () at /usr/lib/libQt5XcbQpa.so.5
#56 0x00007aed80f31199 in ??? () at /usr/lib/libglib-2.0.so.0
#57 0x00007aed80f903bf in ??? () at /usr/lib/libglib-2.0.so.0
#58 0x00007aed80f30712 in g_main_context_iteration ()
    at /usr/lib/libglib-2.0.so.0
#59 0x00007aed7aae288c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#60 0x00007aed7aa92774 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#61 0x00007aed7aa93c13 in QCoreApplication::exec() ()
    at /usr/lib/libQt5Core.so.5
#62 0x00007aed7a0de8f0 in ??? ()
    at /usr/lib/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#63 0x00007aedbbba52ed in ??? () at /usr/lib/libpython3.12.so.1.0
#64 0x00007aedbbb8550b in _PyObject_MakeTpCall ()
    at /usr/lib/libpython3.12.so.1.0
#65 0x00007aedbba8bdfa in ??? () at /usr/lib/libpython3.12.so.1.0
#66 0x00007aedbbc3d767 in PyEval_EvalCode () at /usr/lib/libpython3.12.so.1.0
#67 0x00007aedbbc608b7 in ??? () at /usr/lib/libpython3.12.so.1.0
#68 0x00007aedbbc5b9dc in ??? () at /usr/lib/libpython3.12.so.1.0
#69 0x00007aedbbc74f33 in ??? () at /usr/lib/libpython3.12.so.1.0
#70 0x00007aedbbc74346 in _PyRun_SimpleFileObject ()
    at /usr/lib/libpython3.12.so.1.0
#71 0x00007aedbbc73f88 in _PyRun_AnyFileObject ()
    at /usr/lib/libpython3.12.so.1.0
#72 0x00007aedbbc6cc67 in Py_RunMain () at /usr/lib/libpython3.12.so.1.0
#73 0x00007aedbbc28fab in Py_BytesMain () at /usr/lib/libpython3.12.so.1.0
#74 0x00007aedbb841d4a in ??? () at /usr/lib/libc.so.6
#75 0x00007aedbb841e0c in __libc_start_main () at /usr/lib/libc.so.6
#76 0x0000633e4664c045 in _start ()
```

### System Information

OS: Arch Linux
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.10.0

### Steps to Reproduce the Problem

1) select a variable in the variable editor window.
2) right click on it and choose either variable_editor_enable, or variable_editor_disable
3) the program will crash

**Comment by dl1ksv** [comment]
Should be fixed by #7357
