### ISSUE TITLE
grc: Attribute error

### ISSUE THREAD

**Issue by dl1ksv** [gnuradio/gnuradio#7367]
### What happened?

Loading: "/home/schroer/gnuradiocomponents/gnuradio-volker/gr-digital/examples/packet/example_corr_est_and_clock_sync.grc"
vmcircbuf_sysconfig :info: Using gr::vmcircbuf_sysv_shm_factory
>>> Done
Failed to evaluate variable block modulated_sync_word
Traceback (most recent call last):
  File "/usr/local/gnuradio/lib64/python3.12/site-packages/gnuradio/grc/core/FlowGraph.py", line 286, in _reload_variables
    value = eval(variable_block.value, namespace,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'to_basic_block'

### System Information

Linux, F39, build from source

### GNU Radio Version

3.11-git (main)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

Start grc --gtk
Load example_corr_est_and_and_clock_sync.grc from digital/packet
Select the Constellation object hdr_const
disable this block
enable this block again

**Comment by dl1ksv** [comment]
The error message in the terminal is not the real problem.
We have different situations in grc --gtk and grc --qt.
In grc  --gtk the flowgraph remains invalid after reenableing the constellation object. You have to open and close ( with ok) a fg block, to force an additional fg update.

In grc  --qt you get this error message in the terminal, too. But the fg is valid after reenabling the constellation object. No additional upde is required.
