### ISSUE TITLE
Problems using QT GUI Chooser values in Waveform selection of signal source

### ISSUE THREAD

**Issue by reald** [gnuradio/gnuradio#7475]
### What happened?

I want to change in a flow graph the generated waveform of a Signal Source during runtime. So I added a QT GUI Chooser of type "Any" with different options (analog.GR_SIN_WAVE, analog.GR_SAW_WAVE, ...) and used the chooser ID inside the Waveform field of the signal source. 

![image](https://github.com/user-attachments/assets/468b3685-4a57-490a-951e-4503bbcb55d9)

![image](https://github.com/user-attachments/assets/17fa0e14-1346-4fb6-82e1-bb89ce7dec42)

![image](https://github.com/user-attachments/assets/105dff40-ff94-4464-a572-98dcbf8749dd)

Running this flow graph fails:

- Gnuradio v3.11.0.0git-806-g268a6ea2 (Python 3.8.10)

```
Executing: /usr/bin/python3 -u /home/real/waveform_test.py

Traceback (most recent call last):
  File "/home/real/waveform_test.py", line 204, in <module>
    main()
  File "/home/real/waveform_test.py", line 181, in main
    tb = top_block_cls()
  File "/home/real/waveform_test.py", line 75, in __init__
    self._waveform_options = [gr_waveform_t.GR_SIN_WAVE, gr_waveform_t.GR_SAW_WAVE]
NameError: name 'gr_waveform_t' is not defined
```

- Gnuradio 3.10.1.1 (Python 3.10.12)

```
Executing: /usr/bin/python3 -u /tmp/waveform_test.py

  File "/tmp/waveform_test.py", line 86
    self._waveform_options = [<gr_waveform_t.GR_SIN_WAVE: 101>, <gr_waveform_t.GR_SAW_WAVE: 105>]
                              ^
SyntaxError: invalid syntax
```

Complete flow graph for reproducing:
[waveform_test.zip](https://github.com/user-attachments/files/16662645/waveform_test.zip)

### System Information

OS: Ubuntu Linux
GR Installation Method: Latest git version and Ubuntu 22.04 native distro package (both fail but with different error, see below)

### GNU Radio Version

3.11-git (main)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

1. Build flow graph as described (or use the one attached)
2. Run flow graph
3. Syntax error appears

Workaround: It is possible to cast the `analog.GR_SIN_WAVE` parameters to int. So using `int(analog.GR_SIN_WAVE) `inside the chooser will work.

**Comment by willcode** [comment]
Tagged as feature request since this gets into evaluation of Python code, i.e., what are the limits of what can be entered there.
