### ISSUE TITLE
gr_modtool inconsistent language argument check

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio#987]
GR 3.7.9git-232-gcfac81aa
The c++ language option is checked in (at least two) places, but the check is not consistent.  This bug is demonstrated by the following session

<pre><code class="bash">
> gr_modtool -l C++ add new_block
Usage: gr_modtool add [options] <PATTERN> 
 Call "gr_modtool add" without any options to run it interactively.

gr_modtool: error: option -l: invalid choice: 'C++' (choose from 'cpp', 'c++', 'python')

> gr_modtool -l c++ add new_block
GNU Radio module name identified: cuav
('sink', 'source', 'sync', 'decimator', 'interpolator', 'general', 'tagged_stream', 'hier', 'noblock')
Enter block type: tagged_stream
Traceback (most recent call last):
  File "/opt/gnuradio/release/bin/gr_modtool", line 46, in <module>
    main()
  File "/opt/gnuradio/release/bin/gr_modtool", line 37, in main
    modtool.setup(options, args)
  File "/opt/gnuradio/release/lib/python2.7/dist-packages/gnuradio/modtool/modtool_add.py", line 90, in setup
    print "Language: %s" % {'cpp': 'C++', 'python': 'Python'}[self._info['lang']]
KeyError: 'c++'
</code></pre>

**Comment by mbr0wn** [comment]
Author: Martin Braun
Date: Sat, 12 December 2015  1:39:32

- **Category** set to gr-modtool - **Status** changed from New to Assigned - **Assignee** set to Martin Braun
Yep good catch. 's an easy fix.

**Comment by mbr0wn** [comment]
Author: Martin Braun
Date: Sun, 22 May 2016  6:25:15

- **Resolution** set to fixed
[https://github.com/gnuradio/gnuradio/pull/828][1] 

    

  [1]: https://github.com/gnuradio/gnuradio/pull/828
